# Introducción al aprendizaje automatizado (O2026)

## Tutorial 1. WebScraping (Parte 2)

El objetivo de esta segunda parte de la clase es ver cómo extraer datos de internet por medio de Web Scraping. También veremos una mención a los métodos de *sentiment analysis*.

- Web Scraping
- Breve mención a *Sentiment analysis*

### Web Scraping: extrayendo datos de internet

#### ¿Qué es web scraping? 

La práctica de recopilar datos a través de cualquier medio que no sea un programa que interactúa con una API o un humano que usa un navegador web. En general esto se logra mediante un programa automatizado que consulta un servidor web, solicita datos (generalmente en forma de HTML y otros archivos que componen las páginas web) y luego analiza esos datos para extraer la información necesaria.

<font color="gray">
Fuente: Ryan Mitchell (2015). Web Scraping with Python. 
<font>

#### Antes de empezar ⚠️

###### Aspectos éticos y legales del web scraping
Web scraping es la extracción de datos de sitios web, es una forma automática de guardar información que se presenta en nuestro navegador (muy usada tanto en la industria como en la academia). Sus aspectos legales dependerán de cada sitio. Respecto a la ética es importante que nos detengamos a pensar si estamos o no generando algun perjuicio. 

###### No reinventar la rueda
Emprender un proyecto de web scraping a veces es rápido y sencillo, pero en general requiere tiempo y esfuerzo. Siempre es aconsejable asegurarse de que valga la pena y antes iniciar hacerse algunas preguntas:
* ¿La informacion que necesito ya se encuentra disponible? (ej: APIs)
* ¿Vale la pena automatizarlo o es algo que lleva poco trabajo a mano?

#### Conceptos básicos sobre la web

HTML, CSS y JavaScript son los tres lenguajes principales con los que está hecho la parte de la web que vemos (*front-end*).

Una analogía para entender cómo funcionan:
- HTML como la estructura de la casa. Es el código que organiza el contenido
- CSS como la decoración interior y exterior.
- JavaScript como el sistema eléctrico, del agua y otras funcionalidades que hacen una casa habitable

<center>
<img src="https://www.nicepng.com/png/detail/142-1423886_html5-css3-js-html-css-javascript.png" width="400">

<img src="https://geekflare.com/wp-content/uploads/2019/12/css-gif.gif" width="243">


</center>

<br>
<br>

| ESTRUCTURA  | ESTILO | FUNCIONALIDAD|
|-----|----------------| ---------- |
|HTML| CSS | JAVASCRIPT|

Si quieren ver más cómo se unen HTML+CSS+Javascript: https://codepen.io/voubina/pen/gOZGPYx


<font color="gray">    
Fuente de las imágenes: <br>
https://geekflare.com/es/css-formatting-optimization-tools/ <br>
https://www.nicepng.com/ourpic/u2q8i1o0e6q8r5t4_html5-css3-js-html-css-javascript/

Fuente de la información: Instituto Humai - Curso de Automatización
</font>

##### HTML 

- HTML quiere decir: lenguaje de marcado de hipertexto o HyperText Markup Language por sus siglas en inglés. 
- El código  HTML da estructura a los sitios web.
- El código HTML se conforma por distintos elementos que le dicen al navegador cómo mostrar el contenido.
- Esos elementos son etiquetas. Hay etiquetas para indicar qué contenido es un título, un párrafo, un enlace, una imagen, etc.

|Etiqueta (Tag)     |Descripción|
|:--------|:--------|
|`<!DOCTYPE>`  | 	Define el tipo de documento|
|`<html>`      |	Define un documento HTML |
|`<head>`      |	Contiene metadata/información del documento|
|`<title>`     |	Define el títutlo del documento|
|`<body>`      |	Define el cuerpo del documento|
|`<h1>` a `<h6>`|	Define títulos  |
|`<p>`         |	Define un párrafo|
|`<br>`        |	Inserta un salto de línea (line break) |
|`<!--...-->`	 |  Define un comentario|
    
Para saber más sobre HTML podés consultar [acá](https://www.w3schools.com/TAGS/ref_byfunc.asp) la lista de etiquetas de este lenguaje.

###### ¿Cómo consigo el código HTML?

Ahora que sabemos cuál es el componente principal de los sitios webs podemos intentar programar a nuestra computadora para leer HTML y extraer información útil.

Para conseguir el código de un sitio web podemos:
- Ir a herramientas del desarrollador (`ctrl+shift+i`) en el navegador. Igual a hacer click derecho e inspeccionar.
- Presionar `ctrl+u` en el navegador.

Para hacer lo mismo desde Python podemos usar la librería requests (vamos a verlo ahora)

### Primer ejemplo: títulos de noticias

#### **Método: BeautifulSoup**
* Esta librería provee un *parser* de html, o sea un programa que analiza/entiende el código. Así, nos permite hacer consultas más sofisticadas de forma simple, por ejemplo: "buscar todos los títulos h2 del sitio". Librería de Python que sirve para leer y entender el HTML de una página web.

* Se usa para extraer los datos de archivos HTML. Crea un árbol de análisis a partir del código fuente de la página que se puede utilizar para extraer datos de forma jerárquica y más legible.

<center>
<img alt="" width="700" role="presentation" src="https://miro.medium.com/max/700/0*ETFzXPCNHkPpqNv_.png"> <br>

<font color="gray">
Fuente de la información: Instituto Humai - Curso de Automatización
<font>

Empecemos!

In [67]:
!pip install BeautifulSoup4

Requirement already satisfied: BeautifulSoup4 in /opt/anaconda3/lib/python3.13/site-packages (4.12.3)
Requirement already satisfied: soupsieve>1.2 in /opt/anaconda3/lib/python3.13/site-packages (from BeautifulSoup4) (2.5)

In [68]:
#!pip install requests 
#!pip install BeautifulSoup4 
#!pip install pandas
# Nota: si no tienen instaladas las librarías a importar debajo, primero deben instalarlas 
# (para eso, quiten el # y activen las 3 líneas de código de arriba)

import requests #html requestor, libreria para traer el contenido html de una pagina
from bs4 import BeautifulSoup #html parser, lo ordena y deja buscar información facilmente dentro del contenido
import pandas as pd #dataframe manipulator

In [69]:
url = "https://www.lanacion.com.ar/" #la dirección de la página web que vamos a consultar

r = requests.get(url) #traigo el contenido del html. Objeto de tipo "Response" creado por la librería requests.
contenido = r.content  # .content es un atributo del objeto Response, trae el html de la pagina
print(r.content) #esto muestra lo que python recibe con el pedido de la linea anterior

b'<!DOCTYPE html><html lang="es"><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=0.5,maximum-scale=5.0,user-scalable=yes"/><meta name="theme-color" content="#ffffff"/><title>\xc3\x9altimas noticias de Argentina y el mundo - LA NACION</title><link rel="preload" as="image" fetchPriority="high" media="(min-width: 768px)" href="https://www.lanacion.com.ar/resizer/v2/el-presidente-javier-milei-en-el-nuevo-edificio-ISNHQS44FNFKDD3XIS5YRCHLUQ.jpg?auth=9eda49e9dda77f02c81769a108156b699e05c218d2f4137e3beff5aaa9c17273&amp;width=488&amp;height=325&amp;quality=70&amp;smart=true"/><link rel="preload" as="image" fetchPriority="high" media="(max-width: 767px)" href="https://www.lanacion.com.ar/resizer/v2/el-presidente-javier-milei-en-el-nuevo-edificio-ISNHQS44FNFKDD3XIS5YRCHLUQ.jpg?auth=9eda49e9dda77f02c81769a108156b699e05c218d2f4137e3beff5aaa9c17273&amp;width=420&amp;height=280&amp;quality=70&amp;smart=true"/><link rel="preload" as="image" fetchPriority="high" media="(min-width: 1024px)" href="https://www.lanacion.com.ar/resizer/v2/el-jefe-de-gabinete-manuel-adorni-en-el-consulado-O6LZICEMPJAYHEO673EIWEVIUY.jpg?auth=abda6e75bd1ad868d9ddee9a75fd9fad72c3f75aae5632fb7407ea4018ffaed7&amp;width=302&amp;height=201&amp;quality=70&amp;smart=true"/><script id="pageview" type="application/ld+json">{\n  "pagetype": "home"\n}</script><script defer="" id="scriptRegisterPageview" type="text/javascript" src="/pf/resources/js/LN/scriptPageview.min.js?d=1953"></script><style id="critical-fonts">\n@font-face {font-family:\'Prumo\';src:url(\'/pf/resources/fonts/prumo/Prumo-LNVF.woff2?d=1953\') format(\'woff2-variations\'); font-weight: 90; font-display: swap;}\n@font-face {font-family:\'Prumo Italic\';src:url(\'/pf/resources/fonts/prumo/Prumo-ItalicLNVF.woff2?d=1953\') format(\'woff2-variations\'); font-weight: 90; font-display: swap;}\n</style><style id="critical-css">.button{display:inline-flex;align-items:center;justify-content:center;cursor:pointer;width:-moz-max-content;width:max-content;height:-moz-max-content;height:max-content;font-size:.75rem;line-height:1rem;text-transform:uppercase;white-space:nowrap}.button,.button>.icon>svg>path{transition:all .3s ease-in-out}.button:hover{opacity:.8}.button:disabled{opacity:.4;pointer-events:none}.dropdown .dropdown-menu:after{content:"";height:.5rem;width:1.5rem;display:inline-block;position:absolute;bottom:100%;background-image:url(data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iOCIgdmlld0JveD0iMCAwIDI0IDgiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxnIGlkPSJfUGVhayI+CjxwYXRoIGlkPSJCYWNrZ3JvdW5kIiBkPSJNMTQuMTIxMyAyLjEyMTMyTDE5LjEyMTMgNy4xMjEzMkMxOS42ODM5IDcuNjgzOTMgMjAuNDQ3IDggMjEuMjQyNiA4TDIuNzU3MzYgOEMzLjU1MzAxIDggNC4zMTYwNyA3LjY4MzkzIDQuODc4NjggNy4xMjEzMkw5Ljg3ODY4IDIuMTIxMzJDMTEuMDUwMyAwLjk0OTc0OCAxMi45NDk3IDAuOTQ5NzQ1IDE0LjEyMTMgMi4xMjEzMloiIGZpbGw9IiNGRUZFRkUiLz4KPC9nPgo8L3N2Zz4K);background-size:1.5rem .5rem}.dropdown .dropdown-menu:before{content:"";height:.5rem;position:absolute;left:0;bottom:100%;width:100%}.dropdown .dropdown-menu[data-position=left]{left:0}.dropdown .dropdown-menu[data-position=left]:after{left:.6875rem}.dropdown .dropdown-menu[data-position=center],.dropdown .dropdown-menu[data-position=center]::after{left:50%;transform:translate3d(-50%, 0, 0)}.dropdown .dropdown-menu[data-position=right]{right:0}.dropdown .dropdown-menu[data-position=right]::after{right:.6875rem}.dropdown .icon.dropdown-icon{transition-property:transform}.dropdown .icon.dropdown-icon.--rotate{transform:rotate(180deg)}.--grid-jc-start{justify-content:start}.--grid-jc-end{justify-content:end}.--grid-jc-center{justify-content:center}.--grid-jc-stretch{justify-content:stretch}.--grid-jc-around{justify-content:space-around}.--grid-jc-between{justify-content:space-between}.--grid-jc-evenly{justify-content:space-evenly}.--grid-as-start{align-self:start}.--grid-as-end{align-self:end}.--grid-as-center{align-self:center}.--grid-as-stretch{align-self:stretch}.--grid-as-around{align-self:space-around}.--grid-as-between{align-self:space-between}.--grid-as-evenly{align-self:space-evenly}.--grid-ai-start{align-items:start}.--grid-ai-end{align-items:end}.--grid-ai-center{align-items:center}.--grid-ai-stretch{align-items:stretch}.grid{position:relative;display:grid;width:100%;min-width:-moz-min-content;min-width:min-content}.grid.--gap-none{grid-row-gap:none}.grid.--gap-2xs{grid-row-gap:.25rem}.grid.--gap-xs{grid-row-gap:.5rem}.grid.--gap-sm{grid-row-gap:1rem}.grid.--gap-md{grid-row-gap:1.5rem}.grid.--gap-lg{grid-row-gap:2rem}.grid.--gap-xl{grid-row-gap:2.5rem}.grid.--gap-2xl{grid-row-gap:4rem}.grid.--gap-3xl{grid-row-gap:5rem}.grid.--grid-cols-1{grid-template-columns:repeat(1, 1fr);grid-column-gap:16px}.grid.--grid-cols-2{grid-template-columns:repeat(2, 1fr);grid-column-gap:16px}.grid.--grid-cols-3{grid-template-columns:repeat(3, 1fr);grid-column-gap:16px}.grid.--grid-cols-4{grid-template-columns:repeat(4, 1fr);grid-column-gap:16px}.grid.--grid-cols-5{grid-template-columns:repeat(5, 1fr);grid-column-gap:16px}.grid.--grid-cols-6{grid-template-columns:repeat(6, 1fr);grid-column-gap:16px}.grid.--grid-cols-7{grid-template-columns:repeat(7, 1fr);grid-column-gap:16px}.grid.--grid-cols-8{grid-template-columns:repeat(8, 1fr);grid-column-gap:16px}@media(min-width: 48rem){.grid.--grid-cols-md-1{grid-template-columns:repeat(1, 1fr);grid-column-gap:24px}.grid.--grid-cols-md-2{grid-template-columns:repeat(2, 1fr);grid-column-gap:24px}.grid.--grid-cols-md-3{grid-template-columns:repeat(3, 1fr);grid-column-gap:24px}.grid.--grid-cols-md-4{grid-template-columns:repeat(4, 1fr);grid-column-gap:24px}.grid.--grid-cols-md-5{grid-template-columns:repeat(5, 1fr);grid-column-gap:24px}.grid.--grid-cols-md-6{grid-template-columns:repeat(6, 1fr);grid-column-gap:24px}.grid.--grid-cols-md-7{grid-template-columns:repeat(7, 1fr);grid-column-gap:24px}.grid.--grid-cols-md-8{grid-template-columns:repeat(8, 1fr);grid-column-gap:24px}.grid.--grid-cols-md-9{grid-template-columns:repeat(9, 1fr);grid-column-gap:24px}.grid.--grid-cols-md-10{grid-template-columns:repeat(10, 1fr);grid-column-gap:24px}.grid.--grid-cols-md-11{grid-template-columns:repeat(11, 1fr);grid-column-gap:24px}.grid.--grid-cols-md-12{grid-template-columns:repeat(12, 1fr);grid-column-gap:24px}}@media(min-width: 64rem){.grid.--grid-cols-lg-1{grid-template-columns:repeat(1, 1fr);grid-column-gap:24px}.grid.--grid-cols-lg-2{grid-template-columns:repeat(2, 1fr);grid-column-gap:24px}.grid.--grid-cols-lg-3{grid-template-columns:repeat(3, 1fr);grid-column-gap:24px}.grid.--grid-cols-lg-4{grid-template-columns:repeat(4, 1fr);grid-column-gap:24px}.grid.--grid-cols-lg-5{grid-template-columns:repeat(5, 1fr);grid-column-gap:24px}.grid.--grid-cols-lg-6{grid-template-columns:repeat(6, 1fr);grid-column-gap:24px}.grid.--grid-cols-lg-7{grid-template-columns:repeat(7, 1fr);grid-column-gap:24px}.grid.--grid-cols-lg-8{grid-template-columns:repeat(8, 1fr);grid-column-gap:24px}.grid.--grid-cols-lg-9{grid-template-columns:repeat(9, 1fr);grid-column-gap:24px}.grid.--grid-cols-lg-10{grid-template-columns:repeat(10, 1fr);grid-column-gap:24px}.grid.--grid-cols-lg-11{grid-template-columns:repeat(11, 1fr);grid-column-gap:24px}.grid.--grid-cols-lg-12{grid-template-columns:repeat(12, 1fr);grid-column-gap:24px}}@media(min-width: 80rem){.grid.--grid-cols-xl-1{grid-template-columns:repeat(1, 1fr);grid-column-gap:32px}.grid.--grid-cols-xl-2{grid-template-columns:repeat(2, 1fr);grid-column-gap:32px}.grid.--grid-cols-xl-3{grid-template-columns:repeat(3, 1fr);grid-column-gap:32px}.grid.--grid-cols-xl-4{grid-template-columns:repeat(4, 1fr);grid-column-gap:32px}.grid.--grid-cols-xl-5{grid-template-columns:repeat(5, 1fr);grid-column-gap:32px}.grid.--grid-cols-xl-6{grid-template-columns:repeat(6, 1fr);grid-column-gap:32px}.grid.--grid-cols-xl-7{grid-template-columns:repeat(7, 1fr);grid-column-gap:32px}.grid.--grid-cols-xl-8{grid-template-columns:repeat(8, 1fr);grid-column-gap:32px}.grid.--grid-cols-xl-9{grid-template-columns:repeat(9, 1fr);grid-column-gap:32px}.grid.--grid-cols-xl-10{grid-template-columns:repeat(10, 1fr);grid-column-gap:32px}.grid.--grid-cols-xl-11{grid-template-columns:repeat(11, 1fr);grid-column-gap:32px}.grid.--grid-cols-xl-12{grid-template-columns:repeat(12, 1fr);grid-column-gap:32px}.grid.--grid-cols-xl-13{grid-template-columns:repeat(13, 1fr);grid-column-gap:32px}.grid.--grid-cols-xl-14{grid-template-columns:repeat(14, 1fr);grid-column-gap:32px}.grid.--grid-cols-xl-15{grid-template-columns:repeat(15, 1fr);grid-column-gap:32px}.grid.--grid-cols-xl-16{grid-template-columns:repeat(16, 1fr);grid-column-gap:32px}}.grid .grid-item{grid-column:span 8}.grid .grid-item.--col-1{grid-column:span 1}.grid .grid-item.--col-2{grid-column:span 2}.grid .grid-item.--col-3{grid-column:span 3}.grid .grid-item.--col-4{grid-column:span 4}.grid .grid-item.--col-5{grid-column:span 5}.grid .grid-item.--col-6{grid-column:span 6}.grid .grid-item.--col-7{grid-column:span 7}.grid .grid-item.--col-8{grid-column:span 8}@media(min-width: 48rem){.grid .grid-item{grid-column:span 12}.grid .grid-item.--col-md-1{grid-column:span 1}.grid .grid-item.--col-md-2{grid-column:span 2}.grid .grid-item.--col-md-3{grid-column:span 3}.grid .grid-item.--col-md-4{grid-column:span 4}.grid .grid-item.--col-md-5{grid-column:span 5}.grid .grid-item.--col-md-6{grid-column:span 6}.grid .grid-item.--col-md-7{grid-column:span 7}.grid .grid-item.--col-md-8{grid-column:span 8}.grid .grid-item.--col-md-9{grid-column:span 9}.grid .grid-item.--col-md-10{grid-column:span 10}.grid .grid-item.--col-md-11{grid-column:span 11}.grid .grid-item.--col-md-12{grid-column:span 12}}@media(min-width: 64rem){.grid .grid-item.--col-lg-1{grid-column:span 1}.grid .grid-item.--col-lg-2{grid-column:span 2}.grid .grid-item.--col-lg-3{grid-column:span 3}.grid .grid-item.--col-lg-4{grid-column:span 4}.grid .grid-item.--col-lg-5{grid-column:span 5}.grid .grid-item.--col-lg-6{grid-column:span 6}.grid .grid-item.--col-lg-7{grid-column:span 7}.grid .grid-item.--col-lg-8{grid-column:span 8}.grid .grid-item.--col-lg-9{grid-column:span 9}.grid .grid-item.--col-lg-10{grid-column:span 10}.grid .grid-item.--col-lg-11{grid-column:span 11}.grid .grid-item.--col-lg-12{grid-column:span 12}}@media(min-width: 80rem){.grid .grid-item{grid-column:span 16}.grid .grid-item.--col-xl-1{grid-column:span 1}.grid .grid-item.--col-xl-2{grid-column:span 2}.grid .grid-item.--col-xl-3{grid-column:span 3}.grid .grid-item.--col-xl-4{grid-column:span 4}.grid .grid-item.--col-xl-5{grid-column:span 5}.grid .grid-item.--col-xl-6{grid-column:span 6}.grid .grid-item.--col-xl-7{grid-column:span 7}.grid .grid-item.--col-xl-8{grid-column:span 8}.grid .grid-item.--col-xl-9{grid-column:span 9}.grid .grid-item.--col-xl-10{grid-column:span 10}.grid .grid-item.--col-xl-11{grid-column:span 11}.grid .grid-item.--col-xl-12{grid-column:span 12}.grid .grid-item.--col-xl-13{grid-column:span 13}.grid .grid-item.--col-xl-14{grid-column:span 14}.grid .grid-item.--col-xl-15{grid-column:span 15}.grid .grid-item.--col-xl-16{grid-column:span 16}}.common-header-container{height:var(--header-height, -moz-min-content);height:var(--header-height, min-content)}.common-header-container .common-main-header .content>div{grid-template-columns:[left-start] var(--header-outer-spacing, auto) [center-start] 2fr [center-end] var(--header-outer-spacing, auto) [right-end];grid-template-rows:[main-start] 1fr [main-end]}.common-header-container .common-main-header .content>div .left-options{grid-column:left-start/center-start}.common-header-container .common-main-header .content>div .center-options{grid-column:var(--center-options-grid-column, center-start/center-end)}.common-header-container .common-main-header .content>div .right-options{grid-column:center-end/right-end}.common-header-container .common-main-header .content>div .search-container{grid-column:left-start/right-end}@media(min-width: 80rem){.common-header-container .common-main-header .content>div .search-container{grid-column:center-start/center-end;grid-row:main-start}}.common-header-container .common-main-header .content>div .bottom-options{grid-column:left-start/right-end}.icon{transition:.3s ease-in-out;display:inline-flex;justify-content:center;align-items:center}.icon.--hasWrapper{box-sizing:content-box;border-radius:50%;aspect-ratio:1/1}.icon>svg{width:inherit;height:inherit;vertical-align:top}.icon.--icon-8{width:.5rem;height:.5rem}.icon.--icon-8.--hasWrapper{padding:.25rem}.icon.--icon-12{width:.75rem;height:.75rem}.icon.--icon-12.--hasWrapper{padding:.25rem}.icon.--icon-16{width:1rem;height:1rem}.icon.--icon-16.--hasWrapper{padding:.5rem}.icon.--icon-18{width:1.125rem;height:1.125rem}.icon.--icon-18.--hasWrapper{padding:.5rem}.icon.--icon-20{width:1.25rem;height:1.25rem}.icon.--icon-20.--hasWrapper{padding:.5rem}.icon.--icon-24{width:1.5rem;height:1.5rem}.icon.--icon-24.--hasWrapper{padding:.5rem}.icon.--icon-28{width:1.75rem;height:1.75rem}.icon.--icon-28.--hasWrapper{padding:.5rem}.icon.--icon-32{width:2rem;height:2rem}.icon.--icon-32.--hasWrapper{padding:.75rem}.icon.--icon-36{width:2.25rem;height:2.25rem}.icon.--icon-36.--hasWrapper{padding:.75rem}.icon.--icon-40{width:2.5rem;height:2.5rem}.icon.--icon-40.--hasWrapper{padding:1rem}.icon.--icon-44{width:2.75rem;height:2.75rem}.icon.--icon-44.--hasWrapper{padding:1rem}.icon.--icon-48{width:3rem;height:3rem}.icon.--icon-48.--hasWrapper{padding:1rem}.icon.--light svg>path{fill:#fff}.icon.--dark svg>path{fill:#272727}.icon.--gray svg>path{fill:#919191}.icon.--gray-600 svg>path{fill:#5a5a5a}.icon.--warning svg>path{fill:#fdb727}.icon.--primary svg>path{fill:#126fff}.icon.--success svg>path{fill:#22b120}.icon.--danger svg>path{fill:#f44336}.icon.--violet svg>path{fill:#00033a}.icon.--inherit svg>path{fill:currentColor}.image{transition:all .2s ease-in-out}.image.--contain{-o-object-fit:contain;object-fit:contain}.image.--cover{-o-object-fit:cover;object-fit:cover}.image.--fill{-o-object-fit:fill;object-fit:fill}.link{cursor:pointer;color:#0250c9}.link.--unstyled{color:inherit}.link.--block{display:block}.link.--disabled{opacity:.4;pointer-events:none}@media(min-width: 64rem){.link:hover{opacity:.8}}.ln-placeholder{width:100%;background-color:var(--light-neutral-200)}.dialog{max-width:unset;max-height:unset;inset-block-start:unset;inset-block-end:0;--_background-dialog: var(--background-dialog, rgba(0, 0, 0, 0.5))}.dialog::backdrop{background-color:var(--_background-dialog);opacity:1}.dialog[data-position=bottom]{inset-block-end:0}.dialog[data-position=left]{inset-inline-start:0}.dialog[data-position=right]{inset-inline-start:unset;inset-inline-end:0}.dialog[data-position=top]{inset-block-start:0}.dialog[data-position=center],.dialog[data-position=full]{inset:0;margin:auto}.ln-video{width:100%;-o-object-fit:cover;object-fit:cover}.media-scroller [data-scroller=track]{display:grid;grid-auto-flow:column;grid-auto-columns:calc(var(--scroller-element-columns, 2)/var(--scroller-columns, 8)*100% - var(--scroller-gap, 16px)*(1 - var(--scroller-element-columns, 2)/var(--scroller-columns, 8)));gap:var(--scroller-gap, 16px);overflow-x:auto;overflow-y:hidden;overscroll-behavior-inline:contain;scroll-snap-type:inline mandatory;-ms-overflow-style:none;scrollbar-width:none}.media-scroller [data-scroller=track]::-webkit-scrollbar{display:none}.media-scroller [data-scroller=track]>[data-scroller=element]{scroll-snap-align:start}@media screen and (max-width: 1279px){.media-scroller [data-scroller=track]>[data-scroller=element].--x-scroll-boundary-swipe{scroll-snap-stop:always}}.media-scroller [data-scroller=track].--full-width{width:calc(100% + var(--spacing)*2);padding-inline:var(--spacing);scroll-padding-inline:var(--spacing);transform:translate3d(calc(-1 * var(--spacing)), 0, 0)}.media-scroller [data-scroller=arrow]{top:44%}.media-scroller [data-scroller=arrow]:hover{opacity:1}@media screen and (max-width: 1279px){.media-scroller [data-scroller=arrow]{display:none}}.media-scroller [data-scroller-direction=next]{transform:translate3d(50%, -50%, 0);right:0}.media-scroller [data-scroller-direction=prev]{transform:translate3d(-50%, -50%, 0);left:0}@media(max-width: 767px){.media-scroller.hide-mobile [data-scroller=track]{grid-auto-flow:row;grid-auto-columns:100%;grid-row-gap:var(--scroller-vertical-gap, 16px)}.media-scroller.hide-mobile [data-scroller=progress]{display:none}}.tooltip.--with-arrow{--_arrow-spacing: 0.75rem}.tooltip.--with-arrow:after{content:"";position:absolute;width:var(--_arrow-spacing);height:var(--_arrow-spacing);border-top-left-radius:.25rem;background-color:inherit;border-left:inherit;border-top:inherit;bottom:var(--_bottom);right:var(--_right);left:var(--_left);top:var(--_top);translate:var(--_translate);rotate:calc(var(--_rotate)*45deg)}.tooltip.--with-arrow[data-position^=top]{--_bottom: 0;--_rotate: 5}.tooltip.--with-arrow[data-position=top-center]{--_left: 50%;--_translate: -50% 50%}.tooltip.--with-arrow[data-position=top-left]{--_left: var(--_arrow-spacing);--_translate: 0 50%}.tooltip.--with-arrow[data-position=top-right]{--_right: var(--_arrow-spacing);--_translate: 0 50%}.tooltip.--with-arrow[data-position^=bottom]{--_top: 0;--_rotate: 1}.tooltip.--with-arrow[data-position=bottom-center]{--_left: 50%;--_translate: -50% -50%}.tooltip.--with-arrow[data-position=bottom-left]{--_left: var(--_arrow-spacing);--_translate: 0 -50%}.tooltip.--with-arrow[data-position=bottom-right]{--_right: var(--_arrow-spacing);--_translate: 0 -50%}.tooltip.--with-arrow[data-position^=left]{--_right: 0;--_rotate: 3}.tooltip.--with-arrow[data-position=left-center]{--_top: 50%;--_translate: 50% -50%}.tooltip.--with-arrow[data-position=left-top]{--_top: var(--_arrow-spacing);--_translate: 50% 0}.tooltip.--with-arrow[data-position=left-bottom]{--_bottom: var(--_arrow-spacing);--_translate: 50% 0}.tooltip.--with-arrow[data-position^=right]{--_left: 0;--_rotate: 7}.tooltip.--with-arrow[data-position=right-center]{--_top: 50%;--_translate: -50% -50%}.tooltip.--with-arrow[data-position=right-top]{--_top: var(--_arrow-spacing);--_translate: -50% 0}.tooltip.--with-arrow[data-position=right-bottom]{--_bottom: var(--_arrow-spacing);--_translate: -50% 0}@keyframes shimmer{100%{transform:translate3d(100%, 0, 0)}}.skeleton-loader{position:relative;background-color:#e6e6e6;overflow:hidden;height:auto}.skeleton-loader:after{content:"";position:absolute;top:0;right:0;bottom:0;left:0;transform:translate3d(-100%, 0, 0);background-image:linear-gradient(90deg, rgba(242, 242, 242, 0) 0, rgba(242, 242, 242, 0.2) 10%, rgba(242, 242, 242, 0.5) 30%, rgba(242, 242, 242, 0));animation:shimmer 2s infinite}.skeleton-loader.--rounded-circle{aspect-ratio:1/1}.skeleton-loader.--square{aspect-ratio:1/1}.skeleton-loader.--fill{width:100%;height:100%}.skeleton-loader.--lines{width:100%}.skeleton-loader.--lines:not(:last-of-type){margin-bottom:.5rem}.skeleton-loader.--lines:last-of-type{width:75%}.ln-advance.--withVideo .lay-container>article .video iframe{width:6.875rem;aspect-ratio:16/9;height:auto}@media(min-width: 48rem){.ln-advance.--withVideo .lay-container>article .video iframe{width:15.625rem}}.ln-banner-container{background:repeating-linear-gradient(45deg, rgba(255, 255, 255, 0.1), rgba(255, 255, 255, 0.1), rgba(255, 255, 255, 0.1), rgba(255, 255, 255, 0.1) 4px, rgba(0, 0, 0, 0.15) 6px);background-color:var(--light-neutral-0);position:relative;display:flex;justify-content:center;align-items:flex-start;width:100%;overflow:hidden;z-index:1;margin-bottom:.75rem;margin-top:3.5rem}.ln-banner-container .ln-banner{width:100%;text-align:center}.ln-banner-container:before{content:"PUBLICIDAD";font-size:.6875rem;line-height:1rem;background:var(--light-neutral-0);display:inline-block;padding:.25rem .5rem;margin:0 auto;position:absolute;top:0;z-index:-1}.ln-banner-container.--logo,.ln-banner-container.--logo_int{position:absolute;margin:0;top:0;left:0;width:100%;height:100%;background:#fff}.ln-banner-c

In [70]:
soup = BeautifulSoup(contenido, "html.parser")
soup

<!DOCTYPE html>
<html lang="es"><head><meta charset="utf-8"/><meta content="width=device-width,initial-scale=1.0,minimum-scale=0.5,maximum-scale=5.0,user-scalable=yes" name="viewport"/><meta content="#ffffff" name="theme-color"/><title>Últimas noticias de Argentina y el mundo - LA NACION</title><link as="image" fetchpriority="high" href="https://www.lanacion.com.ar/resizer/v2/el-presidente-javier-milei-en-el-nuevo-edificio-ISNHQS44FNFKDD3XIS5YRCHLUQ.jpg?auth=9eda49e9dda77f02c81769a108156b699e05c218d2f4137e3beff5aaa9c17273&amp;width=488&amp;height=325&amp;quality=70&amp;smart=true" media="(min-width: 768px)" rel="preload"/><link as="image" fetchpriority="high" href="https://www.lanacion.com.ar/resizer/v2/el-presidente-javier-milei-en-el-nuevo-edificio-ISNHQS44FNFKDD3XIS5YRCHLUQ.jpg?auth=9eda49e9dda77f02c81769a108156b699e05c218d2f4137e3beff5aaa9c17273&amp;width=420&amp;height=280&amp;quality=70&amp;smart=true" media="(max-width: 767px)" rel="preload"/><link as="image" fetchpriority="high" href="https://www.lanacion.com.ar/resizer/v2/el-jefe-de-gabinete-manuel-adorni-en-el-consulado-O6LZICEMPJAYHEO673EIWEVIUY.jpg?auth=abda6e75bd1ad868d9ddee9a75fd9fad72c3f75aae5632fb7407ea4018ffaed7&amp;width=302&amp;height=201&amp;quality=70&amp;smart=true" media="(min-width: 1024px)" rel="preload"/><script id="pageview" type="application/ld+json">{
  "pagetype": "home"
}</script><script defer="" id="scriptRegisterPageview" src="/pf/resources/js/LN/scriptPageview.min.js?d=1953" type="text/javascript"></script><style id="critical-fonts">
@font-face {font-family:'Prumo';src:url('/pf/resources/fonts/prumo/Prumo-LNVF.woff2?d=1953') format('woff2-variations'); font-weight: 90; font-display: swap;}
@font-face {font-family:'Prumo Italic';src:url('/pf/resources/fonts/prumo/Prumo-ItalicLNVF.woff2?d=1953') format('woff2-variations'); font-weight: 90; font-display: swap;}

### Buscamos el primer titulo `<h2>` de manera manual y la pegamos en nuestro Markdown
Seleccionando un título que aparece bajo la etiqueta o tag `h2`, vemos, por ejemplo:

Nota: esto cambia según el día en que hagan el request o pedido (ya que la página de noticias se actualiza)

In [71]:
soup.find_all("h2")

[<h2 class="text ln-text subhead --font-s">En un panel moderado por Martín Varsavsky, la presidenta del New York Stock Exchange y ejecutivos de Dow y Uber hablaron del vínculo entre ambas administraciones</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Control de gestión.<!-- --> </span>Adorni suma poder en el Gobierno: ahora le delegan la supervisión de los gastos del Estado</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Entrevista.<!-- --> </span>Los posibles escenarios que enfrenta Irán y la “falta de estrategia” de EE.UU., según un experto europeo </h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">"No tiene sentido".<!-- --> </span>Milei le habló a Wall Street en tono Broadway</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Senado.<!-- --> </span>Con la tropa propia y de aliados diezmada por viajes, Bullrich posterga las sesiones para la semana próxima</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">¿Acuerdo sin anuncio?<!-- --> </span>Pese a las críticas, el Gobierno saldría al auxilio de la industria textil</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Tras la polémica de los caños indios.<!-- --> </span>Vaca Muerta: anuncian al ganador de una obra clave y puede haber sorpresas</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Estaba en una fiesta.<!-- --> </span>Se tiró de un primer piso y disparó para escapar de la policía, pero terminó muerto a balazos</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Papelón en la Champions.<!-- --> </span>Los groseros errores del arquero de Tottenham: le hicieron tres goles en 15 minutos y el DT lo mandó al vestuario</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Su receta.<!-- --> </span>Revolucionó la educación de un pueblo, ahora influye en todo un país y es también referente en América Latina</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">"Es un actor clave".<!-- --> </span>Chevron destacó el rol global de la Argentina y dijo que está ante una "oportunidad  única"</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">“Aberrante”.<!-- --> </span>Embargan por más de $157.000 millones a la gobernación bonaerense por la contaminación en una cuenca hídrica</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">"Manipulación".<!-- --> </span>El Vaticano intensifica las críticas a EE.UU. y repudia que el conflicto se presente como guerra religiosa</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Líder y espía.<!-- --> </span>Mojtaba Khamenei posee un imperio inmobiliario en Londres, con departamentos frente a la embajada de Israel</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Difundió un audio.<!-- --> </span>El pedido de disculpas de la abogada argentina acusada de racismo en Brasil y el giro en su defensa</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">"Los sentí a todos conmigo”.<!-- --> </span>Candela Cerrone, la atleta argentina que ganó la Maratón de Malvinas y homenajeó a los caídos</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Pese a las pérdidas.<!-- --> </span>Longvie confirma la apertura de una planta de termotanques</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Nueva era en Chile.<!-- --> </span>Kast asume con el desafío de cumplir una ambiciosa agenda en medio de un complicado escenario externo</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Ya en el mercado.<!-- --> </span>Una automotriz lanza la nueva versión de su pickup con precio y equipamiento confirmado</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Importaciones.<!-- --> </span>El equipo económico de Luis Caputo negó un “aluvión” de compras al exterior</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">"Tenes que amar a Nueva York".<!-- --> </span>El baile de Milei en una gala de la comunidad judía durante su visita a Estados Unidos</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Revelación de Zelensky.<!-- --> </span>Estados Unidos propone nuevas negociaciones entre Rusia y Ucrania para intentar frenar cuatro años de guerra</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">"Última pieza del rompecabezas".<!-- --> </span>Pidieron 24 años de cárcel para el narco que, junto con su hermano, era el capo del Bajo Flores</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">“El año arrancó mejor de lo esperado”.<!-- --> </span>Nike acelera su expansión en el país con locales propios y vuelve al fútbol argentino</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">“Se la vio en silla de ruedas”.<!-- --> </span>El retoque estético de Eva De Dominici que terminó con una complicación en su salud</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Juliana Awada.<!-- --> </span>Junto a su hija Antonia, reaparece sonriente en la noche porteña: todas las fotos</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-3xl"><span class="text ln-text lead --prumo --font-extra">Alertas e incertidumbre.<!-- --> </span>En Israel crece el agobio por la guerra con Irán y surge una pregunta incómoda: ¿y ahora qué?</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Conflicto globalizado.<!-- --> </span>El mapa que muestra los más de 20 países involucrados en la guerra de Irán</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">¿Metida de pata?<!-- --> </span>Un mensaje borrado de un funcionario de Trump desata confusión sobre una supuesta operación en el estrecho de Ormuz</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">“Mucho más devastador”.<!-- --> </span>Un recurso más vital que el petróleo emerge como nuevo blanco en la guerra en Medio Oriente</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-2xl"><span class="text ln-text lead --prumo --font-extra">Interna.<!-- --> </span>Karina Milei se opone a la permanencia del “espía” de Santiago Caputo en el Senado</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">"Temor fundado".<!-- --> </span>El Gobierno concedió el estatus de refugiado a un bolsonarista condenado por intentar un golpe de Estado</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Caso Cuadernos.<!-- --> </span>En otro revés para Cristina, el Tribunal rechazó las objeciones y avanza con indagatorias presenciales </h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Interna.<!-- --> </span>La Justicia electoral bajó la lista de Zamora en el PJ de Tigre y la conducción queda para el massismo</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">"Fue más fuerte que el cruce de Milei con Rocca".<!-- --> </span>Tres gobernadores y el debate por quién tiene el mejor vino tinto que se trasladó a Nueva York</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Golpe al bolsillo.<!-- --> </span>Seis de cada 10 asalariados se saltea comidas por dificultades económicas</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-3xl"><span class="text ln-text lead --prumo --font-extra">"Una aventura perfecta".<!-- --> </span>El inesperado romance entre la mujer más famosa de la televisión argentina y el hombre más lindo de Hollywood</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Autopista Rosario - Santa Fe.<!-- --> </span>Al menos dos muertos en un accidente entre un micro y una camioneta </h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">"Me rebajé".<!-- --> </span>Una ex Gran Hermano aseguró haber sido novia de Alberto Fernández y que la ayudó a gestionar licitaciones de Procrear</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Lo daban por extinto.<!-- --> </span>El extraño animal cuyas huellas aparecieron en el norte del país y que mantiene en vilo a los científicos </h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Tras 14 años.<!-- --> </span>Un satélite de la NASA reingresará hoy a la atmósfera terrestre y podría estrellarse contra la Tierra</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">"Tragedia terrible".<!-- --> </span>Le jugaron una broma de mal gusto a su profesor de secundaria y murió</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">"Se cayó del cambiador".<!-- --> </span>La angustia de Muni Seligmann: su bebé de 10 meses sufrió una fractura de cráneo</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">“Relleno de asientos”.<!-- --> </span>¿Por qué las aerolíneas odian a los pasajeros de clase económica básica?</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">En Amazon Prime.<!-- --> </span>La serie de ocho capítulos que indaga en la adolescencia de uno de los mejores detectives de la literatura </h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-3xl"><span class="text ln-text lead --prumo --font-extra">A FONDO<!-- --> </span>"Gracias, señor juez". Tiene síndrome de Down y ganó una difícil pulseada para volver a un colegio común</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-3xl"><span class="text ln-text lead --prumo --font-extra">Comenzó Expoagro.<!-- --> </span>El Gobierno reiteró su compromiso para seguir con la baja de las retenciones y un intendente dejó un fuerte mensaje</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">“Vine con mucho entusiasmo”.<!-- --> </span>Inquietos y sorprendidos, los productores ponen el foco en la inversión en Expoagro</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Largas filas en su stand.<!-- --> </span>El Banco Nación, que marcó un récord en el mercado, lanzó créditos en dólares a tasa cero en Expoagro</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Expoagro.<!-- --> </span>Las mejores fotos de una gran noche por los 20 años de la muestra</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Expoagro.<!-- --> </span>Cuatro referentes debatieron sobre tecnología, innovación y los desafíos que se vienen </h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-3xl"><span class="text ln-text lead --prumo --font-extra">Aforo reducido.<!-- --> </span>Qué capacidad dispuso el Gobierno de la Ciudad para el partido entre Huracán y River en el Ducó</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">¡126 partidos seguidos!<!-- --> </span>El impresionante récord con el que el MVP de la NBA igualó a la leyenda de los 100 puntos</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Rival de Argentina.<!-- --> </span>El ex compañero del Dibu Martínez y el niño prodigio del Bayern que podrán ser convocados en Austria</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-3xl"><span class="text ln-text lead --prumo --font-extra">Al Caribe.<!-- --> </span>El solitario viaje de 6400 kilómetros de ‘Diana’, la tortuga boba rescatada en España que cruzó el Atlántico</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">"Se sintieron cómodos".<!-- --> </span>Kansas City, la ciudad de los búnkers más poderosos del Mundial 2026: Argentina, Países Bajos e Inglaterra</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">"Rebalsados de amor".<!-- --> </span>Benjamín Amadeo fue papá por segunda vez: el peculiar nombre que eligió</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Ciudad.<!-- --> </span>En pocos meses, cuatro fachadas fotografiadas para un libro sobre arquitectura desaparecieron o enfrentan su final</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">“Una pesadilla”.<!-- --> </span>El film basado en un héroe de los 80 que fue el punto más bajo en la carrera de un actor y que hoy es de culto</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">“Envejecer no es un castigo”.<!-- --> </span>Cecilia Bolocco reapareció fabulosa en un evento en Los Ángeles junto a Demi Moore</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">"No le interesan a nadie".<!-- --> </span>De Timothée Chalamet a Jessie Buckley, cómo funcionan las campañas de desprestigio que cambian el rumbo de los premios Oscar</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Uno por uno.<!-- --> </span>Quiénes son los finalistas de MasterChef Celebrity y cuáles son sus chances de ganar</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">“El diablo me obligó a hacerlo”.<!-- --> </span>Sangre, exorcismos y la sombra del demonio detrás de un crimen que heló a los Estados Unidos</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Qué veo.<!-- --> </span>La historia real que arrasa en Netflix: la doble vida del ciudadano que traicionó la confianza de todos  </h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Por una patente de 1876.<!-- --> </span>No fue su único creador ni le puso nombre, pero su apellido quedó asociado para siempre con él</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Hace 23 años.<!-- --> </span>La historia de amor jamás contada entre Andrea del Boca y Sofovich: “¿Si estamos enamorados? Ojalá" </h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Frenar la ceguera.<!-- --> </span>Científicos argentinos usan IA para la detección precoz de enfermedades de la vista </h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Agua caliente en ayunas.<!-- --> </span>La nueva bebida viral de TikTok que promete mejorar la digestión</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">¿Romance oficial?<!-- --> </span>Quién es Sofía Smaldone, la mujer que acompañó a Macri en el casamiento de su sobrino con Emily Lucius</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">"Una tragedia enorme".<!-- --> </span>Joshua Jackson rompió el silencio sobre la muerte de James Van Der Beek</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Trivia.<!-- --> </span>¿En qué año votaron por primera vez las mujeres en la Argentina?</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Sostén.<!-- --> </span>Cómo funciona el sistema neerlandés único en el mundo para ayudar a las madres primerizas</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Listas en 6 meses.<!-- --> </span>Casas contenedor: los precios, los metros cuadrados y las ventajas </h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">"No te lo voy a avalar".<!-- --> </span>Mariano Iúdica escupió a un conductor durante una entrevista</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Propiedades.<!-- --> </span>Cuánto cuesta alquilar un dos y un tres ambientes y cuánto aumentó en el último mes</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Tras la exención de Ganancias.<!-- --> </span>Alquileres: un especialista analiza si al dueño le conviene ser monotributista o no</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Summit de Aviación y Turismo.<!-- --> </span>LA NACION pionera, prepara la segunda edición del encuentro más influyente de la industria</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Iván Nahas.<!-- --> </span>Del primer departamento que diseñó entre amigos a su regreso a Experiencia Living</h2>,
 <h2 class="text ln-text title --prumo --font-medium --font-3xl"><span class="text ln-text lead --prumo --font-extra">"Llegué con un inglés tarzanesco".<!-- --> </span>Habló Alan Faena y confesó su plan para que Nueva York vuelva a ser la ciudad que nunca duerme</h2>,

Ejemplo 1

<h2 class="text ln-text subhead --font-s">En un panel moderado por Martín Varsavsky, la presidenta del New York Stock Exchange y ejecutivos de Dow y Uber hablaron del vínculo entre ambas administraciones</h2>

Ejemplo 2

<h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Control de gestión.<!-- --> </span>Adorni suma poder en el Gobierno: ahora le delegan la supervisión de los gastos del Estado</h2>

Ejemplo 3

<h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">El brazo inversor del Banco Mundial.<!-- --> 
</span>Anuncian préstamos por US$400 millones para Rio Tinto y hasta US$5000 millones en minería</h2>

#### Ejercicio: Encontrar el cuarto titulo bajo `<h2>`

Resolver Aqui:

### Opción A - Usando find y find_all

In [74]:
# Dentro de la sopa, busco los elementos que contienen la información que necesito
# Buscamos el elemento <h2> indicando la clase (class). Escribo class_ porque "class" es una palabra reservada en Python
h2_element = soup.find('h2', class_='text ln-text title --prumo --font-medium --font-m-l')

# Obtenemos el texto del elemento <h2> 
h2_text = h2_element.text.strip()  # strip() permite remover espacios sobrantes

#print(h2_element)
print('\n', h2_text)

 Control de gestión. Adorni suma poder en el Gobierno: ahora le delegan la supervisión de los gastos del Estado

In [76]:
# Obtuvimos el *primer* elemento de la página con ese tag. Pero queremos hacerlo para todos los títulos...
# El método "find_all" busca TODOS los elementos de la página con ese tag y devuelve una lista que los contiene 
# (en realidad devuelve un objeto de la clase "bs4.element.ResultSet")
h2_elements = soup.find_all('h2')

#print(type(h2_elements))
print('\n', h2_elements)

 [<h2 class="text ln-text subhead --font-s">En un panel moderado por Martín Varsavsky, la presidenta del New York Stock Exchange y ejecutivos de Dow y Uber hablaron del vínculo entre ambas administraciones</h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Control de gestión.<!-- --> </span>Adorni suma poder en el Gobierno: ahora le delegan la supervisión de los gastos del Estado</h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Entrevista.<!-- --> </span>Los posibles escenarios que enfrenta Irán y la “falta de estrategia” de EE.UU., según un experto europeo </h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">"No tiene sentido".<!-- --> </span>Milei le habló a Wall Street en tono Broadway</h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Senado.<!-- --> </span>Con la tropa propia y de aliados diezmada por viajes, Bullrich posterga las sesiones para la semana próxima</h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">¿Acuerdo sin anuncio?<!-- --> </span>Pese a las críticas, el Gobierno saldría al auxilio de la industria textil</h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Tras la polémica de los caños indios.<!-- --> </span>Vaca Muerta: anuncian al ganador de una obra clave y puede haber sorpresas</h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Estaba en una fiesta.<!-- --> </span>Se tiró de un primer piso y disparó para escapar de la policía, pero terminó muerto a balazos</h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Papelón en la Champions.<!-- --> </span>Los groseros errores del arquero de Tottenham: le hicieron tres goles en 15 minutos y el DT lo mandó al vestuario</h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Su receta.<!-- --> </span>Revolucionó la educación de un pueblo, ahora influye en todo un país y es también referente en América Latina</h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">"Es un actor clave".<!-- --> </span>Chevron destacó el rol global de la Argentina y dijo que está ante una "oportunidad  única"</h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">“Aberrante”.<!-- --> </span>Embargan por más de $157.000 millones a la gobernación bonaerense por la contaminación en una cuenca hídrica</h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">"Manipulación".<!-- --> </span>El Vaticano intensifica las críticas a EE.UU. y repudia que el conflicto se presente como guerra religiosa</h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Líder y espía.<!-- --> </span>Mojtaba Khamenei posee un imperio inmobiliario en Londres, con departamentos frente a la embajada de Israel</h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Difundió un audio.<!-- --> </span>El pedido de disculpas de la abogada argentina acusada de racismo en Brasil y el giro en su defensa</h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">"Los sentí a todos conmigo”.<!-- --> </span>Candela Cerrone, la atleta argentina que ganó la Maratón de Malvinas y homenajeó a los caídos</h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Pese a las pérdidas.<!-- --> </span>Longvie confirma la apertura de una planta de termotanques</h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Nueva era en Chile.<!-- --> </span>Kast asume con el desafío de cumplir una ambiciosa agenda en medio de un complicado escenario externo</h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Ya en el mercado.<!-- --> </span>Una automotriz lanza la nueva versión de su pickup con precio y equipamiento confirmado</h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Importaciones.<!-- --> </span>El equipo económico de Luis Caputo negó un “aluvión” de compras al exterior</h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">"Tenes que amar a Nueva York".<!-- --> </span>El baile de Milei en una gala de la comunidad judía durante su visita a Estados Unidos</h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Revelación de Zelensky.<!-- --> </span>Estados Unidos propone nuevas negociaciones entre Rusia y Ucrania para intentar frenar cuatro años de guerra</h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">"Última pieza del rompecabezas".<!-- --> </span>Pidieron 24 años de cárcel para el narco que, junto con su hermano, era el capo del Bajo Flores</h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">“El año arrancó mejor de lo esperado”.<!-- --> </span>Nike acelera su expansión en el país con locales propios y vuelve al fútbol argentino</h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">“Se la vio en silla de ruedas”.<!-- --> </span>El retoque estético de Eva De Dominici que terminó con una complicación en su salud</h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Juliana Awada.<!-- --> </span>Junto a su hija Antonia, reaparece sonriente en la noche porteña: todas las fotos</h2>, <h2 class="text ln-text title --prumo --font-medium --font-3xl"><span class="text ln-text lead --prumo --font-extra">Alertas e incertidumbre.<!-- --> </span>En Israel crece el agobio por la guerra con Irán y surge una pregunta incómoda: ¿y ahora qué?</h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Conflicto globalizado.<!-- --> </span>El mapa que muestra los más de 20 países involucrados en la guerra de Irán</h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">¿Metida de pata?<!-- --> </span>Un mensaje borrado de un funcionario de Trump desata confusión sobre una supuesta operación en el estrecho de Ormuz</h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">“Mucho más devastador”.<!-- --> </span>Un recurso más vital que el petróleo emerge como nuevo blanco en la guerra en Medio Oriente</h2>, <h2 class="text ln-text title --prumo --font-medium --font-2xl"><span class="text ln-text lead --prumo --font-extra">Interna.<!-- --> </span>Karina Milei se opone a la permanencia del “espía” de Santiago Caputo en el Senado</h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">"Temor fundado".<!-- --> </span>El Gobierno concedió el estatus de refugiado a un bolsonarista condenado por intentar un golpe de Estado</h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Caso Cuadernos.<!-- --> </span>En otro revés para Cristina, el Tribunal rechazó las objeciones y avanza con indagatorias presenciales </h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Interna.<!-- --> </span>La Justicia electoral bajó la lista de Zamora en el PJ de Tigre y la conducción queda para el massismo</h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">"Fue más fuerte que el cruce de Milei con Rocca".<!-- --> </span>Tres gobernadores y el debate por quién tiene el mejor vino tinto que se trasladó a Nueva York</h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Golpe al bolsillo.<!-- --> </span>Seis de cada 10 asalariados se saltea comidas por dificultades económicas</h2>, <h2 class="text ln-text title --prumo --font-medium --font-3xl"><span class="text ln-text lead --prumo --font-extra">"Una aventura perfecta".<!-- --> </span>El inesperado romance entre la mujer más famosa de la televisión argentina y el hombre más lindo de Hollywood</h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Autopista Rosario - Santa Fe.<!-- --> </span>Al menos dos muertos en un accidente entre un micro y una camioneta </h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">"Me rebajé".<!-- --> </span>Una ex Gran Hermano aseguró haber sido novia de Alberto Fernández y que la ayudó a gestionar licitaciones de Procrear</h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Lo daban por extinto.<!-- --> </span>El extraño animal cuyas huellas aparecieron en el norte del país y que mantiene en vilo a los científicos </h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Tras 14 años.<!-- --> </span>Un satélite de la NASA reingresará hoy a la atmósfera terrestre y podría estrellarse contra la Tierra</h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">"Tragedia terrible".<!-- --> </span>Le jugaron una broma de mal gusto a su profesor de secundaria y murió</h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">"Se cayó del cambiador".<!-- --> </span>La angustia de Muni Seligmann: su bebé de 10 meses sufrió una fractura de cráneo</h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">“Relleno de asientos”.<!-- --> </span>¿Por qué las aerolíneas odian a los pasajeros de clase económica básica?</h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">En Amazon Prime.<!-- --> </span>La serie de ocho capítulos que indaga en la adolescencia de uno de los mejores detectives de la literatura </h2>, <h2 class="text ln-text title --prumo --font-medium --font-3xl"><span class="text ln-text lead --prumo --font-extra">A FONDO<!-- --> </span>"Gracias, señor juez". Tiene síndrome de Down y ganó una difícil pulseada para volver a un colegio común</h2>, <h2 class="text ln-text title --prumo --font-medium --font-3xl"><span class="text ln-text lead --prumo --font-extra">Comenzó Expoagro.<!-- --> </span>El Gobierno reiteró su compromiso para seguir con la baja de las retenciones y un intendente dejó un fuerte mensaje</h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">“Vine con mucho entusiasmo”.<!-- --> </span>Inquietos y sorprendidos, los productores ponen el foco en la inversión en Expoagro</h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Largas filas en su stand.<!-- --> </span>El Banco Nación, que marcó un récord en el mercado, lanzó créditos en dólares a tasa cero en Expoagro</h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Expoagro.<!-- --> </span>Las mejores fotos de una gran noche por los 20 años de la muestra</h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Expoagro.<!-- --> </span>Cuatro referentes debatieron sobre tecnología, innovación y los desafíos que se vienen </h2>, <h2 class="text ln-text title --prumo --font-medium --font-3xl"><span class="text ln-text lead --prumo --font-extra">Aforo reducido.<!-- --> </span>Qué capacidad dispuso el Gobierno de la Ciudad para el partido entre Huracán y River en el Ducó</h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">¡126 partidos seguidos!<!-- --> </span>El impresionante récord con el que el MVP de la NBA igualó a la leyenda de los 100 puntos</h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Rival de Argentina.<!-- --> </span>El ex compañero del Dibu Martínez y el niño prodigio del Bayern que podrán ser convocados en Austria</h2>, <h2 class="text ln-text title --prumo --font-medium --font-3xl"><span class="text ln-text lead --prumo --font-extra">Al Caribe.<!-- --> </span>El solitario viaje de 6400 kilómetros de ‘Diana’, la tortuga boba rescatada en España que cruzó el Atlántico</h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">"Se sintieron cómodos".<!-- --> </span>Kansas City, la ciudad de los búnkers más poderosos del Mundial 2026: Argentina, Países Bajos e Inglaterra</h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">"Rebalsados de amor".<!-- --> </span>Benjamín Amadeo fue papá por segunda vez: el peculiar nombre que eligió</h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Ciudad.<!-- --> </span>En pocos meses, cuatro fachadas fotografiadas para un libro sobre arquitectura desaparecieron o enfrentan su final</h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">“Una pesadilla”.<!-- --> </span>El film basado en un héroe de los 80 que fue el punto más bajo en la carrera de un actor y que hoy es de culto</h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">“Envejecer no es un castigo”.<!-- --> </span>Cecilia Bolocco reapareció fabulosa en un evento en Los Ángeles junto a Demi Moore</h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">"No le interesan a nadie".<!-- --> </span>De Timothée Chalamet a Jessie Buckley, cómo funcionan las campañas de desprestigio que cambian el rumbo de los premios Oscar</h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Uno por uno.<!-- --> </span>Quiénes son los finalistas de MasterChef Celebrity y cuáles son sus chances de ganar</h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">“El diablo me obligó a hacerlo”.<!-- --> </span>Sangre, exorcismos y la sombra del demonio detrás de un crimen que heló a los Estados Unidos</h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Qué veo.<!-- --> </span>La historia real que arrasa en Netflix: la doble vida del ciudadano que traicionó la confianza de todos  </h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Por una patente de 1876.<!-- --> </span>No fue su único creador ni le puso nombre, pero su apellido quedó asociado para siempre con él</h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Hace 23 años.<!-- --> </span>La historia de amor jamás contada entre Andrea del Boca y Sofovich: “¿Si estamos enamorados? Ojalá" </h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Frenar la ceguera.<!-- --> </span>Científicos argentinos usan IA para la detección precoz de enfermedades de la vista </h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Agua caliente en ayunas.<!-- --> </span>La nueva bebida viral de TikTok que promete mejorar la digestión</h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">¿Romance oficial?<!-- --> </span>Quién es Sofía Smaldone, la mujer que acompañó a Macri en el casamiento de su sobrino con Emily Lucius</h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">"Una tragedia enorme".<!-- --> </span>Joshua Jackson rompió el silencio sobre la muerte de James Van Der Beek</h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Trivia.<!-- --> </span>¿En qué año votaron por primera vez las mujeres en la Argentina?</h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Sostén.<!-- --> </span>Cómo funciona el sistema neerlandés único en el mundo para ayudar a las madres primerizas</h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Listas en 6 meses.<!-- --> </span>Casas contenedor: los precios, los metros cuadrados y las ventajas </h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">"No te lo voy a avalar".<!-- --> </span>Mariano Iúdica escupió a un conductor durante una entrevista</h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Propiedades.<!-- --> </span>Cuánto cuesta alquilar un dos y un tres ambientes y cuánto aumentó en el último mes</h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Tras la exención de Ganancias.<!-- --> </span>Alquileres: un especialista analiza si al dueño le conviene ser monotributista o no</h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Summit de Aviación y Turismo.<!-- --> </span>LA NACION pionera, prepara la segunda edición del encuentro más influyente de la industria</h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Iván Nahas.<!-- --> </span>Del primer departamento que diseñó entre amigos a su regreso a Experiencia Living</h2>, <h2 class="text ln-text title --prumo --font-medium --font-3xl"><span class="text ln-text lead --prumo --font-extra">"Llegué con un inglés tarzanesco".<!-- --> </span>Habló Alan Faena y confesó su plan para que Nueva York vuelva a ser la ciudad que nunca duerme</h2>, <h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Día del Guitarrista.<!-- --> </span>El nacimiento de Pappo y la historia de su último show, marcado por una tregua histórica con Charly G

In [77]:
# Extraemos el texto de cada elemento <h2> e imprimimos
for h2_element in h2_elements: 
    h2_text = h2_element.text.strip()
    print(h2_text)

# Aclaración: el nombre del ítem por el que iteramos puede ser el que nosotros queramos, por ejemplo: i
for i in h2_elements: 
    h2_text = i.text.strip()
    print(h2_text)

En un panel moderado por Martín Varsavsky, la presidenta del New York Stock Exchange y ejecutivos de Dow y Uber hablaron del vínculo entre ambas administraciones
Control de gestión. Adorni suma poder en el Gobierno: ahora le delegan la supervisión de los gastos del Estado
Entrevista. Los posibles escenarios que enfrenta Irán y la “falta de estrategia” de EE.UU., según un experto europeo
"No tiene sentido". Milei le habló a Wall Street en tono Broadway
Senado. Con la tropa propia y de aliados diezmada por viajes, Bullrich posterga las sesiones para la semana próxima
¿Acuerdo sin anuncio? Pese a las críticas, el Gobierno saldría al auxilio de la industria textil
Tras la polémica de los caños indios. Vaca Muerta: anuncian al ganador de una obra clave y puede haber sorpresas
Estaba en una fiesta. Se tiró de un primer piso y disparó para escapar de la policía, pero terminó muerto a balazos
Papelón en la Champions. Los groseros errores del arquero de Tottenham: le hicieron tres goles en 15 minutos y el DT lo mandó al vestuario
Su receta. Revolucionó la educación de un pueblo, ahora influye en todo un país y es también referente en América Latina
"Es un actor clave". Chevron destacó el rol global de la Argentina y dijo que está ante una "oportunidad  única"
“Aberrante”. Embargan por más de $157.000 millones a la gobernación bonaerense por la contaminación en una cuenca hídrica
"Manipulación". El Vaticano intensifica las críticas a EE.UU. y repudia que el conflicto se presente como guerra religiosa
Líder y espía. Mojtaba Khamenei posee un imperio inmobiliario en Londres, con departamentos frente a la embajada de Israel
Difundió un audio. El pedido de disculpas de la abogada argentina acusada de racismo en Brasil y el giro en su defensa
"Los sentí a todos conmigo”. Candela Cerrone, la atleta argentina que ganó la Maratón de Malvinas y homenajeó a los caídos
Pese a las pérdidas. Longvie confirma la apertura de una planta de termotanques
Nueva era en Chile. Kast asume con el desafío de cumplir una ambiciosa agenda en medio de un complicado escenario externo
Ya en el mercado. Una automotriz lanza la nueva versión de su pickup con precio y equipamiento confirmado
Importaciones. El equipo económico de Luis Caputo negó un “aluvión” de compras al exterior
"Tenes que amar a Nueva York". El baile de Milei en una gala de la comunidad judía durante su visita a Estados Unidos
Revelación de Zelensky. Estados Unidos propone nuevas negociaciones entre Rusia y Ucrania para intentar frenar cuatro años de guerra
"Última pieza del rompecabezas". Pidieron 24 años de cárcel para el narco que, junto con su hermano, era el capo del Bajo Flores
“El año arrancó mejor de lo esperado”. Nike acelera su expansión en el país con locales propios y vuelve al fútbol argentino
“Se la vio en silla de ruedas”. El retoque estético de Eva De Dominici que terminó con una complicación en su salud
Juliana Awada. Junto a su hija Antonia, reaparece sonriente en la noche porteña: todas las fotos
Alertas e incertidumbre. En Israel crece el agobio por la guerra con Irán y surge una pregunta incómoda: ¿y ahora qué?
Conflicto globalizado. El mapa que muestra los más de 20 países involucrados en la guerra de Irán
¿Metida de pata? Un mensaje borrado de un funcionario de Trump desata confusión sobre una supuesta operación en el estrecho de Ormuz
“Mucho más devastador”. Un recurso más vital que el petróleo emerge como nuevo blanco en la guerra en Medio Oriente
Interna. Karina Milei se opone a la permanencia del “espía” de Santiago Caputo en el Senado
"Temor fundado". El Gobierno concedió el estatus de refugiado a un bolsonarista condenado por intentar un golpe de Estado
Caso Cuadernos. En otro revés para Cristina, el Tribunal rechazó las objeciones y avanza con indagatorias presenciales
Interna. La Justicia electoral bajó la lista de Zamora en el PJ de Tigre y la conducción queda para el massismo
"Fue más fuerte que el cruce de Milei con Rocca". Tres gobernadores y el debate por quién tiene el mejor vino tinto que se trasladó a Nueva York
Golpe al bolsillo. Seis de cada 10 asalariados se saltea comidas por dificultades económicas
"Una aventura perfecta". El inesperado romance entre la mujer más famosa de la televisión argentina y el hombre más lindo de Hollywood
Autopista Rosario - Santa Fe. Al menos dos muertos en un accidente entre un micro y una camioneta
"Me rebajé". Una ex Gran Hermano aseguró haber sido novia de Alberto Fernández y que la ayudó a gestionar licitaciones de Procrear
Lo daban por extinto. El extraño animal cuyas huellas aparecieron en el norte del país y que mantiene en vilo a los científicos
Tras 14 años. Un satélite de la NASA reingresará hoy a la atmósfera terrestre y podría estrellarse contra la Tierra
"Tragedia terrible". Le jugaron una broma de mal gusto a su profesor de secundaria y murió
"Se cayó del cambiador". La angustia de Muni Seligmann: su bebé de 10 meses sufrió una fractura de cráneo
“Relleno de asientos”. ¿Por qué las aerolíneas odian a los pasajeros de clase económica básica?
En Amazon Prime. La serie de ocho capítulos que indaga en la adolescencia de uno de los mejores detectives de la literatura
A FONDO "Gracias, señor juez". Tiene síndrome de Down y ganó una difícil pulseada para volver a un colegio común
Comenzó Expoagro. El Gobierno reiteró su compromiso para seguir con la baja de las retenciones y un intendente dejó un fuerte mensaje
“Vine con mucho entusiasmo”. Inquietos y sorprendidos, los productores ponen el foco en la inversión en Expoagro
Largas filas en su stand. El Banco Nación, que marcó un récord en el mercado, lanzó créditos en dólares a tasa cero en Expoagro
Expoagro. Las mejores fotos de una gran noche por los 20 años de la muestra
Expoagro. Cuatro referentes debatieron sobre tecnología, innovación y los desafíos que se vienen
Aforo reducido. Qué capacidad dispuso el Gobierno de la Ciudad para el partido entre Huracán y River en el Ducó
¡126 partidos seguidos! El impresionante récord con el que el MVP de la NBA igualó a la leyenda de los 100 puntos
Rival de Argentina. El ex compañero del Dibu Martínez y el niño prodigio del Bayern que podrán ser convocados en Austria
Al Caribe. El solitario viaje de 6400 kilómetros de ‘Diana’, la tortuga boba rescatada en España que cruzó el Atlántico
"Se sintieron cómodos". Kansas City, la ciudad de los búnkers más poderosos del Mundial 2026: Argentina, Países Bajos e Inglaterra
"Rebalsados de amor". Benjamín Amadeo fue papá por segunda vez: el peculiar nombre que eligió
Ciudad. En pocos meses, cuatro fachadas fotografiadas para un libro sobre arquitectura desaparecieron o enfrentan su final
“Una pesadilla”. El film basado en un héroe de los 80 que fue el punto más bajo en la carrera de un actor y que hoy es de culto
“Envejecer no es un castigo”. Cecilia Bolocco reapareció fabulosa en un evento en Los Ángeles junto a Demi Moore
"No le interesan a nadie". De Timothée Chalamet a Jessie Buckley, cómo funcionan las campañas de desprestigio que cambian el rumbo de los premios Oscar
Uno por uno. Quiénes son los finalistas de MasterChef Celebrity y cuáles son sus chances de ganar
“El diablo me obligó a hacerlo”. Sangre, exorcismos y la sombra del demonio detrás de un crimen que heló a los Estados Unidos
Qué veo. La historia real que arrasa en Netflix: la doble vida del ciudadano que traicionó la confianza de todos
Por una patente de 1876. No fue su único creador ni le puso nombre, pero su apellido quedó asociado para siempre con él
Hace 23 años. La historia de amor jamás contada entre Andrea del Boca y Sofovich: “¿Si estamos enamorados? Ojalá"
Frenar la ceguera. Científicos argentinos usan IA para la detección precoz de enfermedades de la vista
Agua caliente en ayunas. La nueva bebida viral de TikTok que promete mejorar la digestión
¿Romance oficial? Quién es Sofía Smaldone, la mujer que acompañó a Macri en el casamiento de su sobrino con Emily Lucius
"Una tragedia enorme". Joshua Jackson rompió el silencio sobre la muerte de James Van Der Beek
Trivia. ¿En qué año votaron por primera vez las mujeres en la Argentina?
Sostén. Cómo funciona el sistema neerlandés único en el mundo para ayudar a las madres primerizas
Listas en 6 meses. Casas contenedor: los precios, los metros cuadrados y las ventajas
"No te lo voy a avalar". Mariano Iúdica escupió a un conductor durante una entrevista
Propiedades. Cuánto cuesta alquilar un dos y un tres ambientes y cuánto aumentó en el último mes
Tras la exención de Ganancias. Alquileres: un especialista analiza si al dueño le conviene ser monotributista o no
Summit de Aviación y Turismo. LA NACION pionera, prepara la segunda edición del encuentro más influyente de la industria
Iván Nahas. Del primer departamento que diseñó entre amigos a su regreso a Experiencia Living
"Llegué con un inglés tarzanesco". Habló Alan Faena y confesó su plan para que Nueva York vuelva a ser la ciudad que nunca duerme
Día del Guitarrista. El nacimiento de Pappo y la historia de su último show, marcado por una tregua histórica con Charly García.
"No estaba en mis planes". Fue una de las voces más prometedoras del nuevo soul, vino varias veces al país y ahora regresa para una celebración muy especial
Es mi sueño. Entre la emoción, el canto y las historias de vida, así fue el nuevo programa de Guido Kaczka
Conocé las promociones y descuentos. Ya están en venta las entradas para Experiencia Living 2026 en Remeros Beach
Sandy Cairncross, expositor de Experiencia Living Remeros Beach. "Me gusta trabajar dentro de una cáscara moderna y darle un giro maximalista"
Leticia Rocco en Experiencia Living. “Vamos a recrear el departamento de un arquitecto, un lugar donde vida y profesión se entrelazan”
Cómo preparar lomo Wellington. El clásico de la cocina inglesa que desafió a los participantes de MasterChef
Nutritivos y esponjosos. Estos buñuelos son un comodín para servir en diferentes comidas
Qué cocinar hoy. 10 recetas fáciles con pollo para resolver el almuerzo o la cena
Trivias
Nexos
Circuitos
Combinadas
La guerra amenaza el plan de Javier Milei
Un punto de inflexión que definirá el mundo para las generaciones futuras
Jubilación: ¿cómo hacer para conservar la obra social?
Un Poder Judicial al borde de la crisis
Banquinas improductivas
El pobrismo es un error
Uno por uno. Toyota publicó los precios de todos sus modelos: cuáles son los más baratos
Nuevo decreto. Cambios en la VTV: el Gobierno nacional avanza con una reforma del sistema
Montos congelados. Estos son los precios de todas las pickups que se venden en la Argentina
En detalle. El SUV más vendido de la historia de una automotriz llega a la Argentina con una fuerte renovación
Nafta y gasoil. Cómo aprovechar los descuentos de hasta el 30% y reintegros durante marzo
Insólito. Se despertó azul, fue a la guardia médica de urgencia y el diagnóstico que recibió lo dejó atónito
Nuevo proyecto. La decisión que tomó la dirigencia de Boca sobre los frentistas que rodean a La Bombonera
La foto. El emotivo reencuentro de Luciano Castro con sus hijos tras su internación
El audio. El impactante momento en que una orca imita el habla humana
Enterneció las redes. Antonela Roccuzzo festejó el cumple de Ciro, el menor de los Messi, y sorprendió con lo grande que está
Avance. Los científicos lograron “entrar” en la mente de los ratones y ver el mundo como ellos
¿Qué profesiones van a desaparecer con la IA? La respuesta de uno de los expertos argentinos más escuchados
Según Anthropic. Las diez profesiones más expuestas a IA
Luego del acuerdo con OpenAI. Anthropic demanda a EE.UU. para evitar que su IA entre a la lista negra del gobierno
Paso a paso. Cómo activar el "modo tigre azul" de WhatsApp
Trucos. Cómo cortar un PDF en pocos pasos
Detalles. Cómo hacer un vivo en Instagram
Fútbol, guerra y poder. J. K. Rowling y Martín Caparrós encienden el debate en redes sociales
Ya en el mercado. Una automotriz lanza la nueva versión de su pickup con precio y equipamiento confirmado
Entrevista. Los posibles escenarios que enfrenta Irán y la “falta de estrategia” de EE.UU., según un experto europeo
"Tragedia terrible". Le jugaron una broma de mal gusto a su profesor de secundaria y murió
Su receta. Revolucionó la educación de un pueblo, ahora influye en todo un país y es también referente en América Latina
Uno por uno. Los empresarios argentinos que participarán de la "Argentina Week" en Nueva York
15% por cada venta. Cómo funciona el sistema que permite recomendar productos y generar ingresos en Mercado Libre
South Summit Brazil. Cinco startups argentinas competirán en uno de los mayores eventos de innovación de América Latina
Ciudadanía italiana. La Corte Constitucional analizará la Ley 74/2025 en una audiencia clave el 11 de marzo
En fotos. Michelle Pfeiffer sorprende al posar en la alfombra roja junto a su marido, David E. Kelley
"Significa mucho". Lily Collins recuperó su anillo de diamantes de 60 mil dólares: la increíble historia del robo y su nueva vida en Londres
“Viví un infierno”. Se odiaron en el set, las tensiones llegaron a la pantalla y después no se hablaron: cinco coprotagonistas enemistados
"Jugamos a buscar la punta del Obelisco". Cómo son las vistas de 360 grados para redescubrir el skyline porteño y acceder a terrazas privadas
Los secretos de los chefs. Cómo hacer la tortilla perfecta: la proporción entre papa y huevo, con o sin cebolla, y jugosa o bien cocida
De 1880. Tras cinco años cerrado, reabre uno de los bares más antiguos de Buenos Aires
¿Cómo comprar las entradas? Vanesa Martín agotó la primera fecha en Buenos Aires y suma una nueva fecha
Precios sin cambios. Cuánto cuesta el Volkswagen Taos en marzo 2026
Sin cambios. Cuánto cuesta el Toyota Corolla Cross en marzo 2026
Según un estudio internacional. Cuáles son las marcas de autos más confiables y duraderas
Seguirán subiendo en el año. Aumentan las multas en CABA y hay infracciones que llegan hasta $3,8 millones
Presta hasta US$1.000.000. Un banco lanzó los primeros créditos hipotecarios en dólares
Emprendedores. Son argentinos y pasaron de lavar ropa en el microcentro a construir un hotel de lujo con forma de serpiente en la Patagonia
A dos horas de París. Se vende un castillo del siglo XVIII que fue ocupado en la Segunda Guerra Mundial
Se alquila la casa donde vivía en Barrio Parque. Cómo es el petit hotel dónde se mudó Pampita
“La Argentina necesita actividad”. En la tradicional cena de Expoagro los empresarios pidieron mejorar la competitividad
Mensaje. Kicillof le metió presión al Gobierno por las retenciones y expresó que el libre mercado “pasó de moda en el mundo”
“Peor que el caso Fate". Los empleados de Lácteos Verónica alertan que se agravó la situación de la empresa
Ya vende 30 toros por año. Se fue a la Patagonia y comenzó de cero un ambicioso proyecto en un lugar hoy muy pujante
Caldo de huesos.  Por qué tomarlo también cuando hace calor
Ni carne ni suplementos. El alimento con proteína de alta calidad que es fácil de sumar a la dieta
Marina Simian. La científica argentina que trabaja para detectar el cáncer de mama con un simple análisis de sangre
Claves para no repetir el patrón. Los riesgos de los hijos que se hacen cargo emocionalmente de sus padres
"Me siento como en casa". El holandés que abrió un restaurante en la esquina más deseada de la avenida Alvear
“La vida en la ciudad no es lo único que hay”. Pateó el tablero y cambió su vida porteña por un lugar soñado en la costa
En fotos. Todos los invitados a los últimos desfiles de Buenos Aires Fashion Week
Iván Nahas. Del primer departamento que diseñó entre amigos a su regreso a Experiencia Living
En Pilará. una casa brutalista  expone la vida diaria a la naturaleza pero resguarda de la vista de los vecinos
En las sierras. El destino de enormes moles de granito al que sólo se accede caminando
Arquitectura verde. La flor exótica que se volvió la musa de los patios actuales
Límite. Cuánto dinero se puede transferir entre cuentas propias en marzo
Además de la SUBE. Ushuaia suma como medio de pago de los colectivos tarjeta de crédito y de débito
Horóscopo. Las predicciones de Jimena La Torre para la semana del 9 al 15 de marzo
Cifras del mes. Cuánto cobra un obrero metalúrgico en marzo
En un panel moderado por Martín Varsavsky, la presidenta del New York Stock Exchange y ejecutivos de Dow y Uber hablaron del vínculo entre ambas administraciones
Control de gestión. Adorni suma poder en el Gobierno: ahora le delegan la supervisión de los gastos del Estado
Entrevista. Los posibles escenarios que enfrenta Irán y la “falta de estrategia” de EE.UU., según un experto europeo
"No tiene sentido". Milei le habló a Wall Street en tono Broadway
Senado. Con la tropa propia y de aliados diezmada por viajes, Bullrich posterga las sesiones para la semana próxima
¿Acuerdo sin anuncio? Pese a las críticas, el Gobierno saldría al auxilio de la industria textil
Tras la polémica de los caños indios. Vaca Muerta: anuncian al ganador de una obra clave y puede haber sorpresas
Estaba en una fiesta. Se tiró de un primer piso y disparó para escapar de la policía, pero terminó muerto a balazos
Papelón en la Champions. Los groseros errores del arquero de Tottenham: le hicieron tres goles en 15 minutos y el DT lo mandó al vestuario
Su receta. Revolucionó la educación de un pueblo, ahora influye en todo un país y es también referente en América Latina
"Es un actor clave". Chevron destacó el rol global de la Argentina y dijo que está ante una "oportunidad  única"
“Aberrante”. Embargan por más de $157.000 millones a la gobernación bonaerense por la contaminación en una cuenca hídrica
"Manipulación". El Vaticano intensifica las críticas a EE.UU. y repudia que el conflicto se presente como guerra religiosa
Líder y espía. Mojtaba Khamenei posee un imperio inmobiliario en Londres, con departamentos frente a la embajada de Israel
Difundió un audio. El pedido de disculpas de la abogada argentina acusada de racismo en Brasil y el giro en su defensa
"Los sentí a todos conmigo”. Candela Cerrone, la atleta argentina que ganó la Maratón de Malvinas y homenajeó a los caídos
Pese a las pérdidas. Longvie confirma la apertura de una planta de termotanques
Nueva era en Chile. Kast asume con el desafío de cumplir una ambiciosa agenda en medio de un complicado escenario externo
Ya en el mercado. Una automotriz lanza la nueva versión de su pickup con precio y equipamiento confirmado
Importaciones. El equipo económico de Luis Caputo negó un “aluvión” de compras al exterior
"Tenes que amar a Nueva York". El baile de Milei en una gala de la comunidad judía durante su visita a Estados Unidos
Revelación de Zelensky. Estados Unidos propone nuevas negociaciones entre Rusia y Ucrania para intentar frenar cuatro años de guerra
"Última pieza del rompecabezas". Pidieron 24 años de cárcel para el narco que, junto con su hermano, era el capo del Bajo Flores
“El año arrancó mejor de lo esperado”. Nike acelera su expansión en el país con locales propios y vuelve al fútbol argentino
“Se la vio en silla de ruedas”. El retoque estético de Eva De Dominici que terminó con una complicación en su salud
Juliana Awada. Junto a su hija Antonia, reaparece sonriente en la noche porteña: todas las fotos
Alertas e incertidumbre. En Israel crece el agobio por la guerra con Irán y surge una pregunta incómoda: ¿y ahora qué?
Conflicto globalizado. El mapa que muestra los más de 20 países involucrados en la guerra de Irán
¿Metida de pata? Un mensaje borrado de un funcionario de Trump desata confusión sobre una supuesta operación en el estrecho de Ormuz
“Mucho más devastador”. Un recurso más vital que el petróleo emerge como nuevo blanco en la guerra en Medio Oriente
Interna. Karina Milei se opone a la permanencia del “espía” de Santiago Caputo en el Senado
"Temor fundado". El Gobierno concedió el estatus de refugiado a un bolsonarista condenado por intentar un golpe de Estado
Caso Cuadernos. En otro revés para Cristina, el Tribunal rechazó las objeciones y avanza con indagatorias presenciales

In [80]:
# Idealmente, tenemos que guardar estos títulos, queremos analizarlos
titulos = [] # primero creamos una lista

# Extraemos el texto de cada elemento <h2> y ahora guardamos
for h2_element in h2_elements:
    h2_text = h2_element.text.strip() #sacamos el texto del h2 actual y eliminamos los espacios sobrantes al principio y al final
    #print(h2_text)
    
    titulos.append({
        'titular': h2_text #Agregamos a la lista titulos un diccionario con una key llamada 'titular' y como valor el texto del título
    })
#print(titulos)
# Creamos un dataframe a partir de la lista de títulos
titulos_df = pd.DataFrame(titulos)

In [81]:
titulos_df

                                               titular
0    En un panel moderado por Martín Varsavsky, la ...
1    Control de gestión. Adorni suma poder en el Go...
2    Entrevista. Los posibles escenarios que enfren...
3    "No tiene sentido". Milei le habló a Wall Stre...
4    Senado. Con la tropa propia y de aliados diezm...
..                                                 ...
153  Arquitectura verde. La flor exótica que se vol...
154  Límite. Cuánto dinero se puede transferir entr...
155  Además de la SUBE. Ushuaia suma como medio de ...
156  Horóscopo. Las predicciones de Jimena La Torre...
157  Cifras del mes. Cuánto cobra un obrero metalúr...

[158 rows x 1 columns]

### Opción B - Usando select. Defino un selector

Un selector es un descriptor de un elemento de HTML. Como antes usamos la etiqueta (tag) `h2` para encontrar los elementos buscados, un selector combina etiquetas (ej: h2)), clases (class) y ids (tiene que estar antes de class en el caso de los elementos h2) en un solo string para hacer la búsqueda deseada.

Si quieren [acá](https://www.w3schools.com/cssref/css_selectors.php) tienen un enlace para leer más sobre selectores

In [82]:
# Definimos un selector de los objetos que englobe la información buscada
# Vamos a tratar de ser más precisos: vimos que los títulos están bajo los tags h2, pero ahora
# buscaremos indicar en qué objeto se encontraban estos tags h2 
# (y así indicar dónde encontrar los h2 con más precisión)

# En este caso los titulares se encuentran en diferentes "description containers"
desc_selector = '.description-container'; # Identifica todos los elementos HTML con la clase 'description container'. 
# Nota: Antes de la clase se pone un punto

# Con el método select y el selector especificado buscamos todos los elementos deseados
desc_elements = soup.select(desc_selector) # Obtenemos un "bs4.element.ResultSet"

print(type(desc_elements)) # una lista especial (conjunto) de resultados encontrada por BeautifulSoup =  bs4.element.ResultSet
print('\n Primer elemento de los resultados:\n', desc_elements[0]) #mostramos el primer elemento de la lista
print('\n', type(desc_elements[0])) # qué tipo de objeto es ese primer elemento individual = bs4.element.Tag

<class 'bs4.element.ResultSet'>

 Primer elemento de los resultados:
 <section class="description-container relative flex flex-column" href="/economia/argentina-week-en-nueva-york-tres-ceo-globales-destacaron-la-alianza-estrategica-de-milei-con-eeuu-nid10032026/"><span class="ln-badge inline-flex w-fit h-fit ai-center z-1 flex-nowrap text-12 rounded-16 bg-black text-light-0 uppercase py-6 px-8 --negative z-2">LA NACION EN NUEVA YORK</span><h1 class="text ln-text title --prumo --font-medium --font-4xl"><span class="text ln-text lead --prumo --font-extra">Argentina Week.<!-- --> </span>Tres CEO globales destacaron la alianza estratégica de Milei con EE.UU.</h1><h2 class="text ln-text subhead --font-s">En un panel moderado por Martín Varsavsky, la presidenta del New York Stock Exchange y ejecutivos de Dow y Uber hablaron del vínculo entre ambas administraciones</h2><div class="marquee-container flex ai-center" title="Por Guillermo Idiart"><div class="marquee-img-container"><img alt="Guillermo Idiart" class="image marquee-img flex --cover" decoding="async" fetchpriority="low" loading="lazy" src="https://resizer.glanacion.com/resizer/v2/https%3A%2F%2Fauthor-service-images-prod-us-east-1.publishing.aws.arc.pub%2Flanacionar%2Ff587ae13-9ebe-4e83-8d8d-c98ec56b81e7.png?auth=f85982ec0e3b19e0f0251da87b01bd45862eb8def8d5cd9116ad84311622f8e8&amp;width=80&amp;quality=70&amp;smart=false"/></div><div class="marquee-text flex --font-2xs w-100 flex-column"><span class="text ln-text author-section">Economía</span><span class="text ln-text marquee">Por <strong>Guillermo Idiart</strong></span></div></div></section>

 <class 'bs4.element.Tag'>

In [83]:
# Una vez obtenidas ya las cajas con los titulares, buscamos los elementos dentro de cada una que contengan los títulos
# Definimos un selector de estos elementos
h2_selector = 'h2' # Identifica todos los elementos HTML cuyo tag sea 'h2'

In [85]:
print(desc_elements[1])
print('\n', desc_elements[1].select(h2_selector))

<section class="description-container relative flex flex-column" href="/politica/adorni-suma-poder-en-el-gobierno-ahora-le-delegan-la-supervision-de-los-gastos-del-estado-nid10032026/"><h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Control de gestión.<!-- --> </span>Adorni suma poder en el Gobierno: ahora le delegan la supervisión de los gastos del Estado</h2><div class="marquee-container flex ai-center" title="Por Cecilia Devanna"><div class="marquee-text flex --font-2xs w-100 flex-column"><span class="text ln-text marquee">Por <strong>Cecilia Devanna</strong></span></div></div></section>

 [<h2 class="text ln-text title --prumo --font-medium --font-m-l"><span class="text ln-text lead --prumo --font-extra">Control de gestión.<!-- --> </span>Adorni suma poder en el Gobierno: ahora le delegan la supervisión de los gastos del Estado</h2>]

In [86]:
# Creamos una lista vacía para guardar los títulos
titulos_sel = [] 

# Realizamos un loop por todas las descripciones encontradas. Y por cada una, ejecutamos una consulta local
# a cada elemento, buscando entonces el título de cada noticia con el selector ya definido
for desc in desc_elements :
    # Nos quedamos con el 1er resultado, ya que asumimos que nuestro selector es suficientemente preciso 
    # como para encontrar solo resultados válidos.
    h2_element = desc.select(h2_selector)[0]
    titular = h2_element.get_text() # Obtenemos el texto

    titulos_sel.append({
        'titular': titular
    })

# Creamos un dataframe con los títulos a partir de la lista
titulos_sel_df = pd.DataFrame(titulos_sel)

In [87]:
titulos_sel_df

                                               titular
0    En un panel moderado por Martín Varsavsky, la ...
1    Control de gestión. Adorni suma poder en el Go...
2    Entrevista. Los posibles escenarios que enfren...
3    "No tiene sentido". Milei le habló a Wall Stre...
4    Senado. Con la tropa propia y de aliados diezm...
..                                                 ...
149  Arquitectura verde. La flor exótica que se vol...
150  Límite. Cuánto dinero se puede transferir entr...
151  Además de la SUBE. Ushuaia suma como medio de ...
152  Horóscopo. Las predicciones de Jimena La Torre...
153  Cifras del mes. Cuánto cobra un obrero metalúr...

[154 rows x 1 columns]

### Análisis de sentimiento de los títulos de noticias

Más información sobre sentiment analysis, acá: https://www.datacamp.com/tutorial/text-analytics-beginners-nltk

In [ ]:
# Si aún no instalaron estas librerías, activar estas líneas de código -quitar #- para instalarlas
#!pip install string
#!pip install pandas
#!pip install nltk
#!pip install stop_words
#!pip install spacy
#!python -m spacy download es_core_news_sm
#!pip uninstall vaderSentiment
#!pip install vader-multi

In [64]:
# Upgrade de paquetes
!pip install --upgrade pandas nltk stop_words spacy vader-multi

Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.13/site-packages (3.0.1)
Requirement already satisfied: nltk in /opt/anaconda3/lib/python3.13/site-packages (3.9.3)
Requirement already satisfied: stop_words in /opt/anaconda3/lib/python3.13/site-packages (2025.11.4)
Requirement already satisfied: spacy in /opt/anaconda3/lib/python3.13/site-packages (3.8.11)
Requirement already satisfied: vader-multi in /opt/anaconda3/lib/python3.13/site-packages (3.2.2.1)
Requirement already satisfied: numpy>=1.26.0 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: click in /opt/anaconda3/lib/python3.13/site-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in /opt/anaconda3/lib/python3.13/site-packages (from nltk) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in /opt/anaconda3/lib/python3.13/site-packages (from nltk) (2024.11.6)
Requirement already satisfied: tqdm in /opt/anaconda3/lib/python3.13/site-packages (from nltk) (4.67.1)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /opt/anaconda3/lib/python3.13/site-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /opt/anaconda3/lib/python3.13/site-packages (from spacy) (1.0.13)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /opt/anaconda3/lib/python3.13/site-packages (from spacy) (2.0.11)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /opt/anaconda3/lib/python3.13/site-packages (from spacy) (3.0.10)
Requirement already satisfied: thinc<8.4.0,>=8.3.4 in /opt/anaconda3/lib/python3.13/site-packages (from spacy) (8.3.6)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /opt/anaconda3/lib/python3.13/site-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /opt/anaconda3/lib/python3.13/site-packages (from spacy) (2.5.1)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /opt/anaconda3/lib/python3.13/site-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.4.2 in /opt/anaconda3/lib/python3.13/site-packages (from spacy) (0.4.3)
Requirement already satisfied: typer-slim<1.0.0,>=0.3.0 in /opt/anaconda3/lib/python3.13/site-packages (from spacy) (0.24.0)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /opt/anaconda3/lib/python3.13/site-packages (from spacy) (2.32.3)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /opt/anaconda3/lib/python3.13/site-packages (from spacy) (2.10.3)
Requirement already satisfied: jinja2 in /opt/anaconda3/lib/python3.13/site-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in /opt/anaconda3/lib/python3.13/site-packages (from spacy) (72.1.0)
Requirement already satisfied: packaging>=20.0 in /opt/anaconda3/lib/python3.13/site-packages (from spacy) (24.2)
Requirement already satisfied: annotated-types>=0.6.0 in /opt/anaconda3/lib/python3.13/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.6.0)
Requirement already satisfied: pydantic-core==2.27.1 in /opt/anaconda3/lib/python3.13/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (2.27.1)
Requirement already satisfied: typing-extensions>=4.12.2 in /opt/anaconda3/lib/python3.13/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.13/site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.13/site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.13/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.13/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2025.8.3)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in /opt/anaconda3/lib/python3.13/site-packages (from thinc<8.4.0,>=8.3.4->spacy) (1.3.0)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /opt/anaconda3/lib/python3.13/site-packages (from thinc<8.4.0,>=8.3.4->spacy) (0.1.5)
Requirement already satisfied: typer>=0.24.0 in /opt/anaconda3/lib/python3.13/site-packages (from typer-slim<1.0.0,>=0.3.0->spacy) (0.24.1)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in /opt/anaconda3/lib/python3.13/site-packages (from weasel<0.5.0,>=0.4.2->spacy) (0.23.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in /opt/anaconda3/lib/python3.13/site-packages (from weasel<0.5.0,>=0.4.2->spacy) (7.4.1)
Requirement already satisfied: wrapt in /opt/anaconda3/lib/python3.13/site-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.4.2->spacy) (1.17.0)
Requirement already satisfied: translatte in /opt/anaconda3/lib/python3.13/site-packages (from vader-multi) (0.1)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: shellingham>=1.3.0 in /opt/anaconda3/lib/python3.13/site-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (1.5.0)
Requirement already satisfied: rich>=12.3.0 in /opt/anaconda3/lib/python3.13/site-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /opt/anaconda3/lib/python3.13/site-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /opt/anaconda3/lib/python3.13/site-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/anaconda3/lib/python3.13/site-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in /opt/anaconda3/lib/python3.13/site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (0.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/anaconda3/lib/python3.13/site-packages (from jinja2->spacy) (3.0.2)

In [65]:
pd.__version__

'3.0.1'

In [66]:
# spacy simpre me genera problemas al importar. Una alternativa es esta celda
#!pip uninstall spacy
#!pip install spacy
!pip uninstall -y spacy
!pip install spacy

Found existing installation: spacy 3.8.11
Uninstalling spacy-3.8.11:
  Successfully uninstalled spacy-3.8.11
Collecting spacy
  Using cached spacy-3.8.11-cp313-cp313-macosx_11_0_arm64.whl.metadata (27 kB)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /opt/anaconda3/lib/python3.13/site-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /opt/anaconda3/lib/python3.13/site-packages (from spacy) (1.0.13)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /opt/anaconda3/lib/python3.13/site-packages (from spacy) (2.0.11)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /opt/anaconda3/lib/python3.13/site-packages (from spacy) (3.0.10)
Requirement already satisfied: thinc<8.4.0,>=8.3.4 in /opt/anaconda3/lib/python3.13/site-packages (from spacy) (8.3.6)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /opt/anaconda3/lib/python3.13/site-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /opt/anaconda3/lib/python3.13/site-packages (from spacy) (2.5.1)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /opt/anaconda3/lib/python3.13/site-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.4.2 in /opt/anaconda3/lib/python3.13/site-packages (from spacy) (0.4.3)
Requirement already satisfied: typer-slim<1.0.0,>=0.3.0 in /opt/anaconda3/lib/python3.13/site-packages (from spacy) (0.24.0)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /opt/anaconda3/lib/python3.13/site-packages (from spacy) (4.67.1)
Requirement already satisfied: numpy>=1.19.0 in /opt/anaconda3/lib/python3.13/site-packages (from spacy) (2.1.3)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /opt/anaconda3/lib/python3.13/site-packages (from spacy) (2.32.3)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /opt/anaconda3/lib/python3.13/site-packages (from spacy) (2.10.3)
Requirement already satisfied: jinja2 in /opt/anaconda3/lib/python3.13/site-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in /opt/anaconda3/lib/python3.13/site-packages (from spacy) (72.1.0)
Requirement already satisfied: packaging>=20.0 in /opt/anaconda3/lib/python3.13/site-packages (from spacy) (24.2)
Requirement already satisfied: annotated-types>=0.6.0 in /opt/anaconda3/lib/python3.13/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.6.0)
Requirement already satisfied: pydantic-core==2.27.1 in /opt/anaconda3/lib/python3.13/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (2.27.1)
Requirement already satisfied: typing-extensions>=4.12.2 in /opt/anaconda3/lib/python3.13/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.13/site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.13/site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.13/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.13/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2025.8.3)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in /opt/anaconda3/lib/python3.13/site-packages (from thinc<8.4.0,>=8.3.4->spacy) (1.3.0)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /opt/anaconda3/lib/python3.13/site-packages (from thinc<8.4.0,>=8.3.4->spacy) (0.1.5)
Requirement already satisfied: typer>=0.24.0 in /opt/anaconda3/lib/python3.13/site-packages (from typer-slim<1.0.0,>=0.3.0->spacy) (0.24.1)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in /opt/anaconda3/lib/python3.13/site-packages (from weasel<0.5.0,>=0.4.2->spacy) (0.23.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in /opt/anaconda3/lib/python3.13/site-packages (from weasel<0.5.0,>=0.4.2->spacy) (7.4.1)
Requirement already satisfied: wrapt in /opt/anaconda3/lib/python3.13/site-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.4.2->spacy) (1.17.0)
Requirement already satisfied: click>=8.2.1 in /opt/anaconda3/lib/python3.13/site-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /opt/anaconda3/lib/python3.13/site-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (1.5.0)
Requirement already satisfied: rich>=12.3.0 in /opt/anaconda3/lib/python3.13/site-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /opt/anaconda3/lib/python3.13/site-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /opt/anaconda3/lib/python3.13/site-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/anaconda3/lib/python3.13/site-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in /opt/anaconda3/lib/python3.13/site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (0.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/anaconda3/lib/python3.13/site-packages (from jinja2->spacy) (3.0.2)
Using cached spacy-3.8.11-cp313-cp313-macosx_11_0_arm64.whl (5.7 MB)
Installing collected packages: spacy
Successfully installed spacy-3.8.11

In [88]:
# Importamos los paquetes a utilizar
import string
import pandas as pd
import nltk # para procesamiento del lenguaje natural 
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from stop_words import get_stop_words
from nltk.stem import WordNetLemmatizer
import spacy # para preprocesamiento en español
from nltk.sentiment.vader import SentimentIntensityAnalyzer 

# ntlk requiere descargar algunos datos adicionales
#nltk.download('all')

# Para trabajar en inglés usar:
#from textblob import TextBlob

Vamos a limpiar los títulos
Como parte del preprocesamiento de la información tenemos los siguientes pasos:
1. Tokenization: Implica dividir el texto en palabras (o tokens) 
2. Eliminar stop words: quitar palabras comunes e irrelevantes que no tienen mucho "sentimiento". Esto permite mejorar la precisión del análisis de sentimiento
3. Lemmatization: reducir las palabras a sus raíces (por ejemplo, eliminando sufijos, pasar de "leyendo" a "leer").

In [89]:
# Veamos la lista de signos de puntuación
print(string.punctuation)
# Como estamos trabajando en español, es conveniente agregar algunos símbolos más a los signos de puntuación
string.punctuation = string.punctuation + '¿¡“”'
print(string.punctuation)

# Cargar palabras vacías en español
stop_words = get_stop_words('spanish')
print(stop_words)

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~¿¡“”
!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~¿¡“”¿¡“”
['a', 'acerca', 'actualmente', 'adelante', 'además', 'adonde', 'áestarían', 'afirmó', 'agregó', 'ahí', 'ahora', 'al', 'algo', 'algún', 'alguna', 'algunas', 'alguno', 'algunos', 'allende', 'alrededor', 'ambos', 'amén', 'ampleamos', 'ante', 'anterior', 'antes', 'añadió', 'apenas', 'aproximadamente', 'aquel', 'aquellas', 'aquellos', 'aqui', 'aquí', 'arriba', 'aseguró', 'así', 'atras', 'aun', 'aún', 'aunque', 'ayer', 'bajo', 'bastante', 'bien', 'buen', 'buena', 'buenas', 'bueno', 'buenos', 'cabe', 'cabo', 'cada', 'casi', 'cerca', 'cierta', 'ciertas', 'cierto', 'ciertos', 'cinco', 'circa', 'comentó', 'como', 'cómo', 'con', 'conmigo', 'connosco', 'conocer', 'conseguimos', 'conseguir', 'considera', 'consideró', 'consigo', 'consigue', 'consiguen', 'consigues', 'contigo', 'contra', 'convosco', 'convusco', 'cosas', 'creo', 'cual', 'cuales', 'cualquier', 'cuando', 'cuanto', 'cuatro', 'cuenta', 'da', 'dado', 'dan', 'dar', 'de', 'debe', 'deben', 'debido', 'decir', 'dejante', 'dejó', 'del', 'delas', 'demás', 'dentro', 'desde', 'después', 'dice', 'dicen', 'dicho', 'dieron', 'diferente', 'diferentes', 'dijeron', 'dijo', 'dio', 'donde', 'dos', 'durante', 'e', 'ejemplo', 'el', 'él', 'ella', 'ellas', 'ello', 'ellos', 'embargo', 'empleais', 'emplean', 'emplear', 'empleas', 'empleo', 'en', 'encima', 'encuentra', 'entonces', 'entre', 'era', 'erais', 'eramos', 'éramos', 'eran', 'erar', 'eras', 'eres', 'es', 'esa', 'esas', 'ese', 'eso', 'esos', 'esta', 'está', 'ésta', 'estaba', 'estabais', 'estábamos', 'estaban', 'estabas', 'estad', 'estada', 'estadas', 'estado', 'estados', 'estais', 'estáis', 'estamos', 'estan', 'están', 'estando', 'estar', 'estará', 'estarán', 'estarás', 'estaré', 'estaréis', 'estaremos', 'estaría', 'estaríais', 'estaríamos', 'estarían', 'estarías', 'estas', 'estás', 'éstas', 'este', 'esté', 'éste', 'estéis', 'estemos', 'estén', 'estés', 'esto', 'estos', 'éstos', 'estoy', 'estuve', 'estuviera', 'estuvierais', 'estuviéramos', 'estuvieran', 'estuvieras', 'estuvieron', 'estuviese', 'estuvieseis', 'estuviésemos', 'estuviesen', 'estuvieses', 'estuvimos', 'estuviste', 'estuvisteis', 'estuvo', 'ex', 'excepto', 'existe', 'existen', 'explicó', 'expresó', 'fin', 'fue', 'fuera', 'fuerais', 'fuéramos', 'fueran', 'fueras', 'fueron', 'fuerza', 'fuese', 'fueseis', 'fuésemos', 'fuesen', 'fueses', 'fui', 'fuimos', 'fuiste', 'fuisteis', 'gran', 'grandes', 'gueno', 'ha', 'habéis', 'haber', 'había', 'habíais', 'habíamos', 'habían', 'habías', 'habida', 'habidas', 'habido', 'habidos', 'habiendo', 'habrá', 'habrán', 'habrás', 'habré', 'habréis', 'habremos', 'habría', 'habríais', 'habríamos', 'habrían', 'habrías', 'hace', 'haceis', 'hacemos', 'hacen', 'hacer', 'hacerlo', 'haces', 'hacia', 'haciendo', 'hago', 'han', 'has', 'hasta', 'hay', 'haya', 'hayáis', 'hayamos', 'hayan', 'hayas', 'haz', 'he', 'hecho', 'hemo', 'hemos', 'hicieron', 'hizo', 'hoy', 'hube', 'hubiera', 'hubierais', 'hubiéramos', 'hubieran', 'hubieras', 'hubieron', 'hubiese', 'hubieseis', 'hubiésemos', 'hubiesen', 'hubieses', 'hubimos', 'hubiste', 'hubisteis', 'hubo', 'igual', 'incluso', 'indicó', 'informó', 'intenta', 'intentais', 'intentamos', 'intentan', 'intentar', 'intentas', 'intento', 'ir', 'junto', 'la', 'lado', 'largo', 'las', 'le', 'les', 'llegó', 'lleva', 'llevar', 'lo', 'los', 'luego', 'lugar', 'manera', 'manifestó', 'más', 'mayor', 'me', 'mediante', 'mejor', 'mencionó', 'menos', 'mi', 'mí', 'mía', 'miar', 'mías', 'mientras', 'mio', 'mío', 'míos', 'mis', 'misma', 'mismas', 'mismo', 'mismos', 'modo', 'modode', 'momento', 'mucha', 'muchas', 'mucho', 'muchos', 'muy', 'na', 'nada', 'nadie', 'ni', 'ningún', 'ninguna', 'ningunas', 'ninguno', 'ningunos', 'no', 'nos', 'nosotras', 'nosotros', 'nuestra', 'nuestras', 'nuestro', 'nuestros', 'nueva', 'nuevas', 'nuevo', 'nuevos', 'nunca', 'o', 'ocho', 'os', 'otra', 'otras', 'otro', 'otros', 'pa', "pa'", 'par', 'para', 'parece', 'parte', 'partir', 'pasada', 'pasado', 'pero', 'pesar', 'poca', 'pocas', 'poco', 'pocos', 'podeis', 'podemos', 'poder', 'podrá', 'podrán', 'podria', 'podría', 'podriais', 'podriamos', 'podrian', 'podrían', 'podrias', 'poner', 'por', 'por qué', 'porque', 'posible', 'primer', 'primera', 'primero', 'primeros', 'principalmente', 'pro', 'propia', 'propias', 'propio', 'propios', 'próximo', 'próximos', 'pudo', 'pueda', 'puede', 'pueden', 'puedo', 'pues', 'que', 'qué', 'quedó', 'queremos', 'quien', 'quién', 'quienes', 'quiere', 'realizado', 'realizar', 'realizó', 'respecto', 'sabe', 'sabeis', 'sabemos', 'saben', 'saber', 'sabes', 'salvo', 'se', 'sea', 'seáis', 'seamos', 'sean', 'seas', 'según', 'segunda', 'segundo', 'seis', 'sentid', 'sentida', 'sentidas', 'sentido', 'sentidos', 'sentir', 'señaló', 'ser', 'será', 'serán', 'serás', 'seré', 'seréis', 'seremos', 'sería', 'seríais', 'seríamos', 'serían', 'serías', 'si', 'sí', 'sido', 'siempre', 'siendo', 'siente', 'siete', 'sigue', 'siguiente', 'sin', 'sino', 'sintiendo', 'so', 'sobre', 'sois', 'sola', 'solamente', 'solas', 'solo', 'sólo', 'solos', 'somos', 'son', 'soy', 'su', 'sus', 'suya', 'suyas', 'suyo', 'suyos', 'tal', 'también', 'tampoco', 'tan', 'tanto', 'te', 'tendrá', 'tendrán', 'tendrás', 'tendré', 'tendréis', 'tendremos', 'tendría', 'tendríais', 'tendríamos', 'tendrían', 'tendrías', 'tened', 'teneis', 'tenéis', 'tenemos', 'tener', 'tenga', 'tengáis', 'tengamos', 'tengan', 'tengas', 'tengo', 'tenía', 'teníais', 'teníamos', 'tenían', 'tenías', 'tenida', 'tenidas', 'tenido', 'tenidos', 'teniendo', 'tercera', 'ti', 'tiempo', 'tiene', 'tienen', 'tienes', 'toda', 'todas', 'todavía', 'todo', 'todos', 'total', 'trabaja', 'trabajais', 'trabajamos', 'trabajan', 'trabajar', 'trabajas', 'trabajo', 'tras', 'trata', 'través', 'tres', 'tu', 'tú', 'tus', 'tuve', 'tuviera', 'tuvierais', 'tuviéramos', 'tuvieran', 'tuvieras', 'tuvieron', 'tuviese', 'tuvieseis', 'tuviésemos', 'tuviesen', 'tuvieses', 'tuvimos', 'tuviste', 'tuvisteis', 'tuvo', 'tuya', 'tuyas', 'tuyo', 'tuyos', 'última', 'ultimar', 'últimas', 'ultimo', 'último', 'últimos', 'un', 'una', 'unas', 'uno', 'unos', 'usa', 'usais', 'usamos', 'usan', 'usar', 'usas', 'uso', 'usted', 'va', 'vais', 'valor', 'vamos', 'van', 'varias', 'varios', 'vaya', 'veces', 'ver', 'verdad', 'verdadera', 'verdadero', 'versus', 'vez', 'vía', 'vosostras', 'vosostros', 'vosotras', 'vosotros', 'voy', 'vuestra', 'vuestras', 'vuestro', 'vuestros', 'vusco', 'y', 'ya', 'yo']

In [90]:
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/lucianaazulramirez/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     /Users/lucianaazulramirez/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/lucianaazulramirez/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     /Users/lucianaazulramirez/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [ ]:
def limpiar_titulos_nltk(titulo): #creamos una función y guardamos la documentación de la función
    '''
    Esta función limpia el texto del título. 
    Convierte texto en tokens, elimina stop words, y transforma palabras en su forma raíz
    para dejar en el texto solo las palabras con mayor contenido.
    Input:
        título (str): Texto del título original
    Output:
        título (str): Texto del título limpio
    '''
   
    # 1. Separar los títulos en tokens (obtenemos una lista con palabras)
    word_tokens = word_tokenize(titulo.lower()) #de "Milei Criticó a Rocca" a "milei criticó a rocca" y a ['milei','criticó','a','rocca']
    
    # 2. Eliminar palabras vacías (stop words) de los títulos
    # Loop por las condiciones
    filtered_tokens = []
    for w in word_tokens:
        # Verificamos tokens contra stop words y puntuación 
        if w not in stop_words and w not in string.punctuation: # si no es "de, la, el, a.." y no es ", . ? !"
            filtered_tokens.append(w) # que la guarde en esta linea nueva -> ['milei','criticó','rocca']
    
    # 3. Lemmatization
    lemmatizer = WordNetLemmatizer() #creo el objeto 
    
    lemmatized_tokens = []
    for w in filtered_tokens:
        lemmatizer.lemmatize(w) #aplicamos la lematización de 'criticó' a 'criticar'
        lemmatized_tokens.append(w)
            
    # Volvemos a armar la oración (concatenamos las palabras separándolas con un espacio)
    return ' '.join(lemmatized_tokens)

In [91]:
# Cargar el modelo para el español y las stop words según spacy
nlp = spacy.load('es_core_news_sm')
stopwords_spacy = spacy.lang.es.stop_words.STOP_WORDS

def limpiar_titulos_spacy(titulo):
    '''
    Esta función limpia el texto del título (usando funcionalidades de la librería spacy). 
    Convierte texto en tokens, elimina stop words, y transforma palabras en su forma raíz
    para dejar en el texto solo las palabras con mayor contenido.
    Input:
        título (str): Texto del título original
    Output:
        título (str): Texto del título limpio
    '''
   
    # Procesar el texto con spaCy
    doc = nlp(titulo.lower())
    #print(doc)
    
    filtered_tokens = []
    lemmas = []
    
    # Pasar a tokens y eliminar puntación y stopwords
    for w in doc:
        if w.text not in stopwords_spacy and not w.is_punct:
            filtered_tokens.append(w.text)
    filtered_doc = ' '.join(filtered_tokens)
    #print(filtered_doc)
    
    # Obtener las formas lematizadas de las palabras
    doc2 = nlp(filtered_doc)
    for w_f in doc2:
        lemmas.append(w_f.lemma_)
    
    # Volvemos a armar la oración (concatenamos las palabras separándolas con un espacio)
    return ' '.join(lemmas)

In [92]:
#Este es un título sucio:
titulos_sel[0]

{'titular': 'En un panel moderado por Martín Varsavsky, la presidenta del New York Stock Exchange y ejecutivos de Dow y Uber hablaron del vínculo entre ambas administraciones'}

In [93]:
#Este es un título limpio:
limpiar_titulos_nltk(titulos_sel[0]['titular'])

'panel moderado martín varsavsky presidenta new york stock exchange ejecutivos dow uber hablaron vínculo ambas administraciones'

In [94]:
#Este es un título limpio:
limpiar_titulos_spacy(titulos_sel[0]['titular'])

'panel moderado martín varsavsky presidenta new york stock exchange ejecutivo dow uber hablar vínculo ambos administración'

#### Ahora vamos a usar sentiment analysis para ver qué tan positivos son los títulos

Vamos a usar la bilioteca NLTK (Natural Language Toolkit) para clasificar los títulos en positivos o negativos. NLTK es una biblioteca de Python muy utilizada en procesamiento de lenguaje natural (NLP). VADER (Valence Aware Dictionary and Sentiment Reasoner) es un módulo específico de NLTK que se utiliza para el análisis de sentimientos.

VADER es una herramienta especialmente diseñada para el análisis de sentimientos en textos. A diferencia de algunos enfoques más generales que utilizan modelos de aprendizaje automático, VADER se basa en un conjunto de reglas y un diccionario que asigna puntuaciones de polaridad a palabras y expresiones. Además, tiene en cuenta factores como las mayúsculas, los signos de puntuación y los emoticonos para evaluar la intensidad del sentimiento.

Las puntuaciones de VADER incluyen la polaridad (positiva, negativa o neutra) y una medida de la intensidad del sentimiento. Es especialmente útil para textos informales o con lenguaje coloquial, como se encuentra comúnmente en redes sociales.

Vamos a probar dos módulos con VADER:
1. con VADER "original". Ver: https://www.nltk.org/_modules/nltk/sentiment/vader.html
2. con VADER "multi". Ver: https://github.com/brunneis/vader-multi
En realidad, ambos buscan hacer los mismo pero los modelos de fondo están entrenados de formas distintas

In [ ]:
import nltk
nltk.download('vader_lexicon')

In [95]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer

# Inicializar el analizador de sentimientos VADER importado desde la librería clásica de NLP
sia = SentimentIntensityAnalyzer()

# Primero veamos un ejemplo
texto_ej_pos = "Me encanta este curso, es genial"
texto_ej_neg = "Odio este curso, es terrible"
texto_ej_neu = "Me da igual el curso"

print(texto_ej_pos, sia.polarity_scores(texto_ej_pos))
print(texto_ej_neg, sia.polarity_scores(texto_ej_neg))
print(texto_ej_neu, sia.polarity_scores(texto_ej_neu))
# Si la variable compound es positiva, el texto es positivo; si es negativa, el texto es negativo 
# Y si se encuentra en el rango del 0 es un mensaje neutro

Me encanta este curso, es genial {'neg': 0.0, 'neu': 0.641, 'pos': 0.359, 'compound': 0.4215}
Odio este curso, es terrible {'neg': 0.437, 'neu': 0.563, 'pos': 0.0, 'compound': -0.4767}
Me da igual el curso {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}

In [96]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer as SentimentIntensityAnalyzerMulti
 
# Inicializar el analizador de sentimientos VADER multilenguaje importado desde vaderSentiment
sia2 = SentimentIntensityAnalyzerMulti()

# Primero veamos un ejemplo
texto_ej_pos = "Me encanta este curso, es genial"
texto_ej_neg = "Odio este curso, es terrible"
texto_ej_neu = "Me da igual el curso"

print(texto_ej_pos, sia2.polarity_scores(texto_ej_pos))
print(texto_ej_neg, sia2.polarity_scores(texto_ej_neg))
print(texto_ej_neu, sia2.polarity_scores(texto_ej_neu))
# Si la variable compound es positiva, el texto es positivo; si es negativa, el texto es negativo 
# Y si se encuentra en el rango del 0 es un mensaje neutro

Me encanta este curso, es genial {'neg': 0.0, 'neu': 0.325, 'pos': 0.675, 'compound': 0.8519}
Odio este curso, es terrible {'neg': 0.63, 'neu': 0.37, 'pos': 0.0, 'compound': -0.7783}
Me da igual el curso {'neg': 0.345, 'neu': 0.655, 'pos': 0.0, 'compound': -0.3875}

Ahora crearemos funciones que, además de dar un valor, clasifiquen en positivo, negativo o neutro

In [97]:
def analizar_sentiment(text):
    # Obtener la polaridad del sentimiento
    sia = SentimentIntensityAnalyzer()
    sentiment_score = sia.polarity_scores(text)

    # Clasificar el sentimiento como positivo, negativo o neutro
    compound_score = sentiment_score['compound']
    if compound_score >= 0.05:
        sentiment = "Positivo"
    elif compound_score <= -0.05:
        sentiment = "Negativo"
    else:
        sentiment = "Neutro"

    return compound_score, sentiment

In [98]:
def analizar_sentiment2(text):
    # Obtener la polaridad del sentimiento
    sia2 = SentimentIntensityAnalyzerMulti()
    sentiment_score = sia2.polarity_scores(text)

    # Clasificar el sentimiento como positivo, negativo o neutro
    compound_score = sentiment_score['compound']
    if compound_score >= 0.05:
        sentiment = "Positivo"
    elif compound_score <= -0.05:
        sentiment = "Negativo"
    else:
        sentiment = "Neutro"

    return compound_score, sentiment

In [99]:
# Ejemplos de uso
compound_score_pos, sentiment_pos = analizar_sentiment(texto_ej_pos)
print(f"Texto: {texto_ej_pos}")
print(f"Puntuación de sentimiento compuesta: {compound_score_pos}")
print(f"Sentimiento: {sentiment_pos}")

compound_score_neg, sentiment_neg = analizar_sentiment(texto_ej_neg)
print(f"\nTexto: {texto_ej_neg}")
print(f"Puntuación de sentimiento compuesta: {compound_score_neg}")
print(f"Sentimiento: {sentiment_neg}")

Texto: Me encanta este curso, es genial
Puntuación de sentimiento compuesta: 0.4215
Sentimiento: Positivo

Texto: Odio este curso, es terrible
Puntuación de sentimiento compuesta: -0.4767
Sentimiento: Negativo

In [100]:
# Ejemplos de uso
compound_score_pos, sentiment_pos = analizar_sentiment2(texto_ej_pos)
print(f"Texto: {texto_ej_pos}")
print(f"Puntuación de sentimiento compuesta: {compound_score_pos}")
print(f"Sentimiento: {sentiment_pos}")

compound_score_neg, sentiment_neg = analizar_sentiment2(texto_ej_neg)
print(f"\nTexto: {texto_ej_neg}")
print(f"Puntuación de sentimiento compuesta: {compound_score_neg}")
print(f"Sentimiento: {sentiment_neg}")

Texto: Me encanta este curso, es genial
Puntuación de sentimiento compuesta: 0.8519
Sentimiento: Positivo

Texto: Odio este curso, es terrible
Puntuación de sentimiento compuesta: -0.7783
Sentimiento: Negativo

In [101]:
# Ahora un ejemplo con un título limpio
print(titulos_sel[0]['titular'], 
      "\n",
      analizar_sentiment(limpiar_titulos_spacy(titulos_sel[0]['titular'])))

En un panel moderado por Martín Varsavsky, la presidenta del New York Stock Exchange y ejecutivos de Dow y Uber hablaron del vínculo entre ambas administraciones
 (0.0, 'Neutro')

In [103]:
# Aplicamos la función para limpiar títulos para tener un columna con títulos limpios
titulos_sel_df['titular_limpio'] = titulos_sel_df['titular'].apply(limpiar_titulos_nltk)
# Vemos el sentiment
titulos_sel_df['sentiment'] = titulos_sel_df['titular_limpio'].apply(analizar_sentiment)
titulos_sel_df['sentiment2'] = titulos_sel_df['titular_limpio'].apply(analizar_sentiment2)

In [104]:
titulos_sel_df

,titular,titular_limpio,sentiment,sentiment2
0,"En un panel moderado por Martín Varsavsky, la ...",panel moderado martín varsavsky presidenta new...,"(0.0, Neutro)","(0.0, Neutro)"
1,Control de gestión. Adorni suma poder en el Go...,control gestión adorni suma gobierno delegan s...,"(0.0, Neutro)","(0.0, Neutro)"
2,Entrevista. Los posibles escenarios que enfren...,entrevista posibles escenarios enfrenta irán f...,"(0.0, Neutro)","(-0.296, Negativo)"
3,"""No tiene sentido"". Milei le habló a Wall Stre...",`` '' milei habló wall street tono broadway,"(0.0, Neutro)","(0.0, Neutro)"
4,Senado. Con la tropa propia y de aliados diezm...,senado tropa aliados diezmada viajes bullrich ...,"(0.0, Neutro)","(-0.2732, Negativo)"
...,...,...,...,...
149,Arquitectura verde. La flor exótica que se vol...,arquitectura verde flor exótica volvió musa pa...,"(0.0, Neutro)","(0.0, Neutro)"
150,Límite. Cuánto dinero se puede transferir entr...,límite cuánto dinero transferir cuentas marzo,"(0.0, Neutro)","(0.0, Neutro)"
151,Además de la SUBE. Ushuaia suma como medio de ...,sube ushuaia suma medio pago colectivos tarjet...,"(0.0, Neutro)","(0.3818, Positivo)"
152,Horóscopo. Las predicciones de Jimena La Torre...,horóscopo predicciones jimena torre semana 9 1...,"(0.0, Neutro)","(0.0, Neutro)"
153,Cifras del mes. Cuánto cobra un obrero metalúr...,cifras mes cuánto cobra obrero metalúrgico marzo,"(0.0, Neutro)","(0.0, Neutro)"

In [105]:
titulos_sel_df['sentiment'].value_counts()

sentiment
(0.0, Neutro)          140
(-0.4767, Negativo)      2
(0.1779, Positivo)       2
(0.4767, Positivo)       1
(0.5267, Positivo)       1
(0.296, Positivo)        1
(0.7184, Positivo)       1
(0.6808, Positivo)       1
(0.2023, Positivo)       1
(0.6124, Positivo)       1
(-0.6249, Negativo)      1
(-0.4019, Negativo)      1
(0.34, Positivo)         1
Name: count, dtype: int64

In [106]:
titulos_sel_df['sentiment2'].value_counts()

sentiment2
(0.0, Neutro)          48
(0.4404, Positivo)      5
(-0.296, Negativo)      4
(0.5106, Positivo)      4
(0.5719, Positivo)      4
                       ..
(-0.25, Negativo)       1
(-0.6597, Negativo)     1
(0.2023, Positivo)      1
(0.3182, Positivo)      1
(0.3818, Positivo)      1
Name: count, Length: 67, dtype: int64

In [107]:
titulos_sel_df.to_excel('titulos.xlsx', index=False)

#### Un ejemplo en inglés usando TextBlob

In [ ]:
from textblob import TextBlob

In [ ]:
# Ejemplo de texto en inglés
texto_ej_1 = "I love learning about Big data"
texto_ej_2 = "I hate learning about Big data"

# Crear un objeto TextBlob con el texto
blob1 = TextBlob(texto_ej_1)

# Obtener la polaridad del sentimiento (-1 a 1)
polarity1 = blob1.sentiment.polarity

# Clasificar el sentimiento como positivo, negativo o neutro
def clasif_polarity(polarity):
    if polarity > 0:
        sentiment = "Positivo"
    elif polarity < 0:
        sentiment = "Negativo"
    else:
        sentiment = "Neutro"
    return sentiment

# Mostrar los resultados
print(f"Texto: {texto_ej_1}")
print(f"Polaridad del sentimiento: {polarity1}")
print(f"Sentimiento: {clasif_polarity(polarity1)}")

### Otro Ejemplo de Web Scraping: Tabla

In [ ]:
import requests #html requestor
from bs4 import BeautifulSoup #html parser
import pandas as pd #dataframe manipulator

In [ ]:
url = 'https://datatables.net/examples/basic_init/zero_configuration.html'

Solicitamos el html del url indicado. El código de respuesta 200 significa que la respuesta del sitio fue exitosa

In [ ]:
response = requests.get(url)
print(response.status_code)

Dividimos el texto con `BeautifulSoup`.

In [ ]:
soup = BeautifulSoup(response.text, 'html.parser')
print(soup)

Se puede observar que la informacion que queremos extraer esta entre las etiquetas llamadas `tr`. Por lo tanto queremos encontrar todas las etiquetas `tr`.

In [ ]:
info = soup.find_all('tr')
info

In [ ]:
print(type(info))
print(type(info[0]))

Podemos ver que todas las observaciones, excepto la primera y la última, contienen la información que necesitamos. También observamos que el nombre, el puesto, el cargo, la edad, la fecha de inicio y el salario siempre tienen el mismo orden. Podemos hacer uso de estos patrones para extraer la información en un marco de datos.

In [ ]:
df = pd.DataFrame(columns=['name', 'position', 'office', 'age', 'start date', 'salary'])

In [ ]:
print(info[1].find_all('td'))

In [ ]:
for i, item in enumerate(info): #enumerate da la posición
    if i != 0 and i != len(info)-1:
        datos_de_fila = item.find_all('td')
        fila = []
        for dato in datos_de_fila:
            fila.append(dato.text)
        print('\nFila:', i)
        print(fila)
        df.loc[i-1] = fila # mencionamos el nombre/etiqueta de las filas que queremos seleccionar

In [ ]:
display(df)

Por último exportamos la información a un archivo `csv`:

In [ ]:
df.to_csv('final_output.csv', index=False)